services:
  db:
    image: mariadb:latest
    container_name: kiwoom_db
    volumes:
      - type: bind
        source: ./mysql
        target: /var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      TZ: Asia/Seoul
    ports:
      - 3306:3306