"""정적 종목정보 API 요청 스펙 정의.

URL: /api/dostk/stkinfo
메뉴: 국내주식 > 종목정보
"""

STKINFO_API_SPECS = [
    {
        'api_id': 'ka00198',
        'name': '실시간종목조회순위',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'qry_tp', 'label': '구분', 'required': True, 'description': '1:1분, 2:10분, 3:1시간, 4:당일 누적, 5:30초'},
        ],
        'request_example': {'qry_tp': ''},
    },
    {
        'api_id': 'ka10001',
        'name': '주식기본정보요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
        ],
        'request_example': {'stk_cd': ''},
    },
    {
        'api_id': 'ka10002',
        'name': '주식거래원요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
        ],
        'request_example': {'stk_cd': ''},
    },
    {
        'api_id': 'ka10003',
        'name': '체결정보요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
        ],
        'request_example': {'stk_cd': ''},
    },
    {
        'api_id': 'ka10013',
        'name': '신용매매동향요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': 'dt', 'label': '일자', 'required': True, 'description': 'YYYYMMDD'},
            {'element': 'qry_tp', 'label': '조회구분', 'required': True, 'description': '1:융자, 2:대주'},
        ],
        'request_example': {'stk_cd': '', 'dt': '', 'qry_tp': ''},
    },
    {
        'api_id': 'ka10015',
        'name': '일별거래상세요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': 'strt_dt', 'label': '시작일자', 'required': True, 'description': 'YYYYMMDD'},
        ],
        'request_example': {'stk_cd': '', 'strt_dt': ''},
    },
    {
        'api_id': 'ka10016',
        'name': '신고저가요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '000:전체, 001:코스피, 101:코스닥'},
            {'element': 'ntl_tp', 'label': '신고저구분', 'required': True, 'description': '1:신고가,2:신저가'},
            {'element': 'high_low_close_tp', 'label': '고저종구분', 'required': True, 'description': '1:고저기준, 2:종가기준'},
            {'element': 'stk_cnd', 'label': '종목조건', 'required': True, 'description': '0:전체조회,1:관리종목제외, 3:우선주제외, 5:증100제외, 6:증100만보기, 7:증40만보기, 8:증30만보기'},
            {'element': 'trde_qty_tp', 'label': '거래량구분', 'required': True, 'description': '00000:전체조회, 00010:만주이상, 00050:5만주이상, 00100:10만주이상, 00150:15만주이상, 00200:20만주이상, 00300:30만주이상, 00500:50만주이상, 01000:백만주이상'},
            {'element': 'crd_cnd', 'label': '신용조건', 'required': True, 'description': '0:전체조회, 1:신용융자A군, 2:신용융자B군, 3:신용융자C군, 4:신용융자D군, 7:신용융자E군, 9:신용융자전체'},
            {'element': 'updown_incls', 'label': '상하한포함', 'required': True, 'description': '0:미포함, 1:포함'},
            {'element': 'dt', 'label': '기간', 'required': True, 'description': '5:5일, 10:10일, 20:20일, 60:60일, 250:250일, 250일까지 입력가능'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'mrkt_tp': '', 'ntl_tp': '', 'high_low_close_tp': '', 'stk_cnd': '', 'trde_qty_tp': '', 'crd_cnd': '', 'updown_incls': '', 'dt': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10017',
        'name': '상하한가요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '000:전체, 001:코스피, 101:코스닥'},
            {'element': 'updown_tp', 'label': '상하한구분', 'required': True, 'description': '1:상한, 2:상승, 3:보합, 4: 하한, 5:하락, 6:전일상한, 7:전일하한'},
            {'element': 'sort_tp', 'label': '정렬구분', 'required': True, 'description': '1:종목코드순, 2:연속횟수순(상위100개), 3:등락률순'},
            {'element': 'stk_cnd', 'label': '종목조건', 'required': True, 'description': '0:전체조회,1:관리종목제외, 3:우선주제외, 4:우선주+관리종목제외, 5:증100제외, 6:증100만 보기, 7:증40만 보기, 8:증30만 보기, 9:증20만 보기, 10:우선주+관리종목+환기종목제외'},
            {'element': 'trde_qty_tp', 'label': '거래량구분', 'required': True, 'description': '00000:전체조회, 00010:만주이상, 00050:5만주이상, 00100:10만주이상, 00150:15만주이상, 00200:20만주이상, 00300:30만주이상, 00500:50만주이상, 01000:백만주이상'},
            {'element': 'crd_cnd', 'label': '신용조건', 'required': True, 'description': '0:전체조회, 1:신용융자A군, 2:신용융자B군, 3:신용융자C군, 4:신용융자D군, 7:신용융자E군, 9:신용융자전체'},
            {'element': 'trde_gold_tp', 'label': '매매금구분', 'required': True, 'description': '0:전체조회, 1:1천원미만, 2:1천원~2천원, 3:2천원~3천원, 4:5천원~1만원, 5:1만원이상, 8:1천원이상'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'mrkt_tp': '', 'updown_tp': '', 'sort_tp': '', 'stk_cnd': '', 'trde_qty_tp': '', 'crd_cnd': '', 'trde_gold_tp': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10018',
        'name': '고저가근접요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'high_low_tp', 'label': '고저구분', 'required': True, 'description': '1:고가, 2:저가'},
            {'element': 'alacc_rt', 'label': '근접율', 'required': True, 'description': '05:0.5 10:1.0, 15:1.5, 20:2.0. 25:2.5, 30:3.0'},
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '000:전체, 001:코스피, 101:코스닥'},
            {'element': 'trde_qty_tp', 'label': '거래량구분', 'required': True, 'description': '00000:전체조회, 00010:만주이상, 00050:5만주이상, 00100:10만주이상, 00150:15만주이상, 00200:20만주이상, 00300:30만주이상, 00500:50만주이상, 01000:백만주이상'},
            {'element': 'stk_cnd', 'label': '종목조건', 'required': True, 'description': '0:전체조회,1:관리종목제외, 3:우선주제외, 5:증100제외, 6:증100만보기, 7:증40만보기, 8:증30만보기'},
            {'element': 'crd_cnd', 'label': '신용조건', 'required': True, 'description': '0:전체조회, 1:신용융자A군, 2:신용융자B군, 3:신용융자C군, 4:신용융자D군, 7:신용융자E군, 9:신용융자전체'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'high_low_tp': '', 'alacc_rt': '', 'mrkt_tp': '', 'trde_qty_tp': '', 'stk_cnd': '', 'crd_cnd': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10019',
        'name': '가격급등락요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '000:전체, 001:코스피, 101:코스닥, 201:코스피200'},
            {'element': 'flu_tp', 'label': '등락구분', 'required': True, 'description': '1:급등, 2:급락'},
            {'element': 'tm_tp', 'label': '시간구분', 'required': True, 'description': '1:분전, 2:일전'},
            {'element': 'tm', 'label': '시간', 'required': True, 'description': '분 혹은 일입력'},
            {'element': 'trde_qty_tp', 'label': '거래량구분', 'required': True, 'description': '00000:전체조회, 00010:만주이상, 00050:5만주이상, 00100:10만주이상, 00150:15만주이상, 00200:20만주이상, 00300:30만주이상, 00500:50만주이상, 01000:백만주이상'},
            {'element': 'stk_cnd', 'label': '종목조건', 'required': True, 'description': '0:전체조회,1:관리종목제외, 3:우선주제외, 5:증100제외, 6:증100만보기, 7:증40만보기, 8:증30만보기'},
            {'element': 'crd_cnd', 'label': '신용조건', 'required': True, 'description': '0:전체조회, 1:신용융자A군, 2:신용융자B군, 3:신용융자C군, 4:신용융자D군, 7:신용융자E군, 9:신용융자전체'},
            {'element': 'pric_cnd', 'label': '가격조건', 'required': True, 'description': '0:전체조회, 1:1천원미만, 2:1천원~2천원, 3:2천원~3천원, 4:5천원~1만원, 5:1만원이상, 8:1천원이상'},
            {'element': 'updown_incls', 'label': '상하한포함', 'required': True, 'description': '0:미포함, 1:포함'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'mrkt_tp': '', 'flu_tp': '', 'tm_tp': '', 'tm': '', 'trde_qty_tp': '', 'stk_cnd': '', 'crd_cnd': '', 'pric_cnd': '', 'updown_incls': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10024',
        'name': '거래량갱신요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '000:전체, 001:코스피, 101:코스닥'},
            {'element': 'cycle_tp', 'label': '주기구분', 'required': True, 'description': '5:5일, 10:10일, 20:20일, 60:60일, 250:250일'},
            {'element': 'trde_qty_tp', 'label': '거래량구분', 'required': True, 'description': '5:5천주이상, 10:만주이상, 50:5만주이상, 100:10만주이상, 200:20만주이상, 300:30만주이상, 500:50만주이상, 1000:백만주이상'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'mrkt_tp': '', 'cycle_tp': '', 'trde_qty_tp': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10025',
        'name': '매물대집중요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '000:전체, 001:코스피, 101:코스닥'},
            {'element': 'prps_cnctr_rt', 'label': '매물집중비율', 'required': True, 'description': '0~100 입력'},
            {'element': 'cur_prc_entry', 'label': '현재가진입', 'required': True, 'description': '0:현재가 매물대 진입 포함안함, 1:현재가 매물대 진입포함'},
            {'element': 'prpscnt', 'label': '매물대수', 'required': True, 'description': '숫자입력'},
            {'element': 'cycle_tp', 'label': '주기구분', 'required': True, 'description': '50:50일, 100:100일, 150:150일, 200:200일, 250:250일, 300:300일'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'mrkt_tp': '', 'prps_cnctr_rt': '', 'cur_prc_entry': '', 'prpscnt': '', 'cycle_tp': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10026',
        'name': '고저PER요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'pertp', 'label': 'PER구분', 'required': True, 'description': '1:저PBR, 2:고PBR, 3:저PER, 4:고PER, 5:저ROE, 6:고ROE'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'pertp': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10028',
        'name': '시가대비등락률요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'sort_tp', 'label': '정렬구분', 'required': True, 'description': '1:시가, 2:고가, 3:저가, 4:기준가'},
            {'element': 'trde_qty_cnd', 'label': '거래량조건', 'required': True, 'description': '0000:전체조회, 0010:만주이상, 0050:5만주이상, 0100:10만주이상, 0500:50만주이상, 1000:백만주이상'},
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '000:전체, 001:코스피, 101:코스닥'},
            {'element': 'updown_incls', 'label': '상하한포함', 'required': True, 'description': '0:불 포함, 1:포함'},
            {'element': 'stk_cnd', 'label': '종목조건', 'required': True, 'description': '0:전체조회, 1:관리종목제외, 4:우선주+관리주제외, 3:우선주제외, 5:증100제외, 6:증100만보기, 7:증40만보기, 8:증30만보기, 9:증20만보기'},
            {'element': 'crd_cnd', 'label': '신용조건', 'required': True, 'description': '0:전체조회, 1:신용융자A군, 2:신용융자B군, 3:신용융자C군, 4:신용융자D군, 7:신용융자E군, 9:신용융자전체'},
            {'element': 'trde_prica_cnd', 'label': '거래대금조건', 'required': True, 'description': '0:전체조회, 3:3천만원이상, 5:5천만원이상, 10:1억원이상, 30:3억원이상, 50:5억원이상, 100:10억원이상, 300:30억원이상, 500:50억원이상, 1000:100억원이상, 3000:300억원이상, 5000:500억원이상'},
            {'element': 'flu_cnd', 'label': '등락조건', 'required': True, 'description': '1:상위, 2:하위'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'sort_tp': '', 'trde_qty_cnd': '', 'mrkt_tp': '', 'updown_incls': '', 'stk_cnd': '', 'crd_cnd': '', 'trde_prica_cnd': '', 'flu_cnd': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10043',
        'name': '거래원매물대분석요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': 'strt_dt', 'label': '시작일자', 'required': True, 'description': 'YYYYMMDD'},
            {'element': 'end_dt', 'label': '종료일자', 'required': True, 'description': 'YYYYMMDD'},
            {'element': 'qry_dt_tp', 'label': '조회기간구분', 'required': True, 'description': '0:기간으로 조회, 1:시작일자, 종료일자로 조회'},
            {'element': 'pot_tp', 'label': '시점구분', 'required': True, 'description': '0:당일, 1:전일'},
            {'element': 'dt', 'label': '기간', 'required': True, 'description': '5:5일, 10:10일, 20:20일, 40:40일, 60:60일, 120:120일'},
            {'element': 'sort_base', 'label': '정렬기준', 'required': True, 'description': '1:종가순, 2:날짜순'},
            {'element': 'mmcm_cd', 'label': '회원사코드', 'required': True, 'description': '회원사 코드는 ka10102 조회'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'stk_cd': '', 'strt_dt': '', 'end_dt': '', 'qry_dt_tp': '', 'pot_tp': '', 'dt': '', 'sort_base': '', 'mmcm_cd': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10052',
        'name': '거래원순간거래량요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'mmcm_cd', 'label': '회원사코드', 'required': True, 'description': '회원사 코드는 ka10102 조회'},
            {'element': 'stk_cd', 'label': '종목코드', 'required': False, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '0:전체, 1:코스피, 2:코스닥, 3:종목'},
            {'element': 'qty_tp', 'label': '수량구분', 'required': True, 'description': '0:전체, 1:1000주, 2:2000주, 3:, 5:, 10:10000주, 30: 30000주, 50: 50000주, 100: 100000주'},
            {'element': 'pric_tp', 'label': '가격구분', 'required': True, 'description': '0:전체, 1:1천원 미만, 8:1천원 이상, 2:1천원 ~ 2천원, 3:2천원 ~ 5천원, 4:5천원 ~ 1만원, 5:1만원 이상'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'mmcm_cd': '', 'mrkt_tp': '', 'qty_tp': '', 'pric_tp': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10054',
        'name': '변동성완화장치발동종목요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '000:전체, 001: 코스피, 101:코스닥'},
            {'element': 'bf_mkrt_tp', 'label': '장전구분', 'required': True, 'description': '0:전체, 1:정규시장,2:시간외단일가'},
            {'element': 'stk_cd', 'label': '종목코드', 'required': False, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)  공백입력시 시장구분으로 설정한 전체종목조회'},
            {'element': 'motn_tp', 'label': '발동구분', 'required': True, 'description': '0:전체, 1:정적VI, 2:동적VI, 3:동적VI + 정적VI'},
            {'element': 'skip_stk', 'label': '제외종목', 'required': True, 'description': '전종목포함 조회시 9개 0으로 설정(000000000),전종목제외 조회시 9개 1으로 설정(111111111),9개 종목조회여부를 조회포함(0), 조회제외(1)로 설정하며 종목순서는 우선주,관리종목,투자경고/위험,투자주의,환기종목,단기과열종목,증거금100%,ETF,ETN가 됨.우선주만 조회시"011111111"", 관리종목만 조회시 ""101111111"" 설정"'},
            {'element': 'trde_qty_tp', 'label': '거래량구분', 'required': True, 'description': '0:사용안함, 1:사용'},
            {'element': 'min_trde_qty', 'label': '최소거래량', 'required': True, 'description': '0 주 이상, 거래량구분이 1일때만 입력(공백허용)'},
            {'element': 'max_trde_qty', 'label': '최대거래량', 'required': True, 'description': '100000000 주 이하, 거래량구분이 1일때만 입력(공백허용)'},
            {'element': 'trde_prica_tp', 'label': '거래대금구분', 'required': True, 'description': '0:사용안함, 1:사용'},
            {'element': 'min_trde_prica', 'label': '최소거래대금', 'required': True, 'description': '0 백만원 이상, 거래대금구분 1일때만 입력(공백허용)'},
            {'element': 'max_trde_prica', 'label': '최대거래대금', 'required': True, 'description': '100000000 백만원 이하, 거래대금구분 1일때만 입력(공백허용)'},
            {'element': 'motn_drc', 'label': '발동방향', 'required': True, 'description': '0:전체, 1:상승, 2:하락'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'mrkt_tp': '', 'bf_mkrt_tp': '', 'motn_tp': '', 'skip_stk': '', 'trde_qty_tp': '', 'min_trde_qty': '', 'max_trde_qty': '', 'trde_prica_tp': '', 'min_trde_prica': '', 'max_trde_prica': '', 'motn_drc': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10055',
        'name': '당일전일체결량요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': 'tdy_pred', 'label': '당일전일', 'required': True, 'description': '1:당일, 2:전일'},
        ],
        'request_example': {'stk_cd': '', 'tdy_pred': ''},
    },
    {
        'api_id': 'ka10058',
        'name': '투자자별일별매매종목요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'strt_dt', 'label': '시작일자', 'required': True, 'description': 'YYYYMMDD'},
            {'element': 'end_dt', 'label': '종료일자', 'required': True, 'description': 'YYYYMMDD'},
            {'element': 'trde_tp', 'label': '매매구분', 'required': True, 'description': '순매도:1, 순매수:2'},
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '001:코스피, 101:코스닥'},
            {'element': 'invsr_tp', 'label': '투자자구분', 'required': True, 'description': '8000:개인, 9000:외국인, 1000:금융투자, 3000:투신, 3100:사모펀드, 5000:기타금융, 4000:은행, 2000:보험, 6000:연기금, 7000:국가, 7100:기타법인, 9999:기관계'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'strt_dt': '', 'end_dt': '', 'trde_tp': '', 'mrkt_tp': '', 'invsr_tp': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka10059',
        'name': '종목별투자자기관별요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'dt', 'label': '일자', 'required': True, 'description': 'YYYYMMDD'},
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': 'amt_qty_tp', 'label': '금액수량구분', 'required': True, 'description': '1:금액, 2:수량'},
            {'element': 'trde_tp', 'label': '매매구분', 'required': True, 'description': '0:순매수, 1:매수, 2:매도'},
            {'element': 'unit_tp', 'label': '단위구분', 'required': True, 'description': '1000:천주, 1:단주'},
        ],
        'request_example': {'dt': '', 'stk_cd': '', 'amt_qty_tp': '', 'trde_tp': '', 'unit_tp': ''},
    },
    {
        'api_id': 'ka10061',
        'name': '종목별투자자기관별합계요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': 'strt_dt', 'label': '시작일자', 'required': True, 'description': 'YYYYMMDD'},
            {'element': 'end_dt', 'label': '종료일자', 'required': True, 'description': 'YYYYMMDD'},
            {'element': 'amt_qty_tp', 'label': '금액수량구분', 'required': True, 'description': '1:금액, 2:수량'},
            {'element': 'trde_tp', 'label': '매매구분', 'required': True, 'description': '0:순매수'},
            {'element': 'unit_tp', 'label': '단위구분', 'required': True, 'description': '1000:천주, 1:단주'},
        ],
        'request_example': {'stk_cd': '', 'strt_dt': '', 'end_dt': '', 'amt_qty_tp': '', 'trde_tp': '', 'unit_tp': ''},
    },
    {
        'api_id': 'ka10084',
        'name': '당일전일체결요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': 'tdy_pred', 'label': '당일전일', 'required': True, 'description': '당일 : 1, 전일 : 2'},
            {'element': 'tic_min', 'label': '틱분', 'required': True, 'description': '0:틱, 1:분'},
            {'element': 'tm', 'label': '시간', 'required': False, 'description': '조회시간 4자리, 오전 9시일 경우 0900, 오후 2시 30분일 경우 1430'},
        ],
        'request_example': {'stk_cd': '', 'tdy_pred': '', 'tic_min': ''},
    },
    {
        'api_id': 'ka10095',
        'name': '관심종목정보요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': '거래소별 종목코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL) 여러개의 종목코드 입력시 | 로 구분'},
        ],
        'request_example': {'stk_cd': ''},
    },
    {
        'api_id': 'ka10099',
        'name': '종목정보 리스트',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '0 : 코스피, 10 : 코스닥, 30 : K-OTC, 50 : 코넥스, 60 : ETN, 70 : 손실제한 ETN, 80 : 금현물, 90 : 변동성 ETN, 2 : 인프라투융자, 3 : ELW, 4 : 뮤추얼펀드, 5 : 신주인수권, 6 : 리츠종목, 7 : 신주인수권증서, 8 : ETF, 9 : 하이일드펀드'},
        ],
        'request_example': {'mrkt_tp': ''},
    },
    {
        'api_id': 'ka10100',
        'name': '종목정보 조회',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': ''},
        ],
        'request_example': {'stk_cd': ''},
    },
    {
        'api_id': 'ka10101',
        'name': '업종코드 리스트',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': '0:코스피(거래소),1:코스닥,2:KOSPI200,4:KOSPI100,7:KRX100(통합지수)'},
        ],
        'request_example': {'mrkt_tp': ''},
    },
    {
        'api_id': 'ka10102',
        'name': '회원사 리스트',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
        ],
        'request_example': {},
    },
    {
        'api_id': 'ka90003',
        'name': '프로그램순매수상위50요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'trde_upper_tp', 'label': '매매상위구분', 'required': True, 'description': '1:순매도상위, 2:순매수상위'},
            {'element': 'amt_qty_tp', 'label': '금액수량구분', 'required': True, 'description': '1:금액, 2:수량'},
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': 'P00101:코스피, P10102:코스닥'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'trde_upper_tp': '', 'amt_qty_tp': '', 'mrkt_tp': '', 'stex_tp': ''},
    },
    {
        'api_id': 'ka90004',
        'name': '종목별프로그램매매현황요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'dt', 'label': '일자', 'required': True, 'description': 'YYYYMMDD'},
            {'element': 'mrkt_tp', 'label': '시장구분', 'required': True, 'description': 'P00101:코스피, P10102:코스닥'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': '1:KRX, 2:NXT 3.통합'},
        ],
        'request_example': {'dt': '', 'mrkt_tp': '', 'stex_tp': ''},
    },
    {
        'api_id': 'kt20016',
        'name': '신용융자 가능종목요청',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'crd_stk_grde_tp', 'label': '신용종목등급구분', 'required': False, 'description': '%:전체, A:A군, B:B군, C:C군, D:D군, E:E군'},
            {'element': 'mrkt_deal_tp', 'label': '시장거래구분', 'required': True, 'description': '%:전체, 1:코스피, 0:코스닥'},
            {'element': 'stk_cd', 'label': '종목코드', 'required': False, 'description': ''},
        ],
        'request_example': {'mrkt_deal_tp': ''},
    },
    {
        'api_id': 'kt20017',
        'name': '신용융자 가능문의',
        'overview': '',
        'url': '/api/dostk/stkinfo',
        'fields': [
            {'element': 'stk_cd', 'label': '종목코드', 'required': True, 'description': ''},
        ],
        'request_example': {'stk_cd': ''},
    },
]
