-- =============================================================
-- trading (/uapi/domestic-stock/v1/trading/) 모듈 DB 스키마
-- source: src/trading/specs_request.py, src/trading/specs_response.py
-- =============================================================

-- 테이블명 규칙: /uapi/domestic-stock/v1/trading/ 이후 전체 경로를 snake_case 로 변환
-- 예: /uapi/domestic-stock/v1/trading/pension/inquire-deposit -> pension_inquire_deposit

DROP TABLE IF EXISTS period_rights CASCADE;
DROP TABLE IF EXISTS inquire_account_balance CASCADE;
DROP TABLE IF EXISTS pension_inquire_deposit CASCADE;
DROP TABLE IF EXISTS order_resv_rvsecncl CASCADE;
DROP TABLE IF EXISTS inquire_credit_psamount CASCADE;
DROP TABLE IF EXISTS intgr_margin CASCADE;
DROP TABLE IF EXISTS pension_inquire_daily_ccld CASCADE;
DROP TABLE IF EXISTS inquire_period_trade_profit CASCADE;
DROP TABLE IF EXISTS order_rvsecncl CASCADE;
DROP TABLE IF EXISTS order_resv_ccnl CASCADE;
DROP TABLE IF EXISTS pension_inquire_psbl_order CASCADE;
DROP TABLE IF EXISTS inquire_balance CASCADE;
DROP TABLE IF EXISTS pension_inquire_present_balance CASCADE;
DROP TABLE IF EXISTS inquire_psbl_order CASCADE;
DROP TABLE IF EXISTS inquire_period_profit CASCADE;
DROP TABLE IF EXISTS order_cash CASCADE;
DROP TABLE IF EXISTS inquire_psbl_sell CASCADE;
DROP TABLE IF EXISTS inquire_daily_ccld CASCADE;
DROP TABLE IF EXISTS inquire_psbl_rvsecncl CASCADE;
DROP TABLE IF EXISTS order_resv CASCADE;
DROP TABLE IF EXISTS order_credit CASCADE;
DROP TABLE IF EXISTS pension_inquire_balance CASCADE;
DROP TABLE IF EXISTS inquire_balance_rlz_pl CASCADE;

-- =============================================================
-- period_rights - 기간별계좌권리현황조회 (CTRGA011R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/period-rights
-- =============================================================
CREATE TABLE IF NOT EXISTS period_rights (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_inqr_dvsn TEXT NULL COMMENT '요청 INQR_DVSN',
    req_cust_rncno25 TEXT NULL COMMENT '요청 CUST_RNCNO25',
    req_hmid TEXT NULL COMMENT '요청 HMID',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_inqr_strt_dt TEXT NULL COMMENT '요청 INQR_STRT_DT',
    req_inqr_end_dt TEXT NULL COMMENT '요청 INQR_END_DT',
    req_rght_type_cd TEXT NULL COMMENT '요청 RGHT_TYPE_CD',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    req_prdt_type_cd TEXT NULL COMMENT '요청 PRDT_TYPE_CD',
    req_ctx_area_nk100 TEXT NULL COMMENT '요청 CTX_AREA_NK100',
    req_ctx_area_fk100 TEXT NULL COMMENT '요청 CTX_AREA_FK100',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_acno10 TEXT NULL COMMENT '응답 acno10',
    rsp_rght_type_cd TEXT NULL COMMENT '응답 rght_type_cd',
    rsp_bass_dt TEXT NULL COMMENT '응답 bass_dt',
    rsp_rght_cblc_type_cd TEXT NULL COMMENT '응답 rght_cblc_type_cd',
    rsp_rptt_pdno TEXT NULL COMMENT '응답 rptt_pdno',
    rsp_pdno TEXT NULL COMMENT '응답 pdno',
    rsp_prdt_type_cd TEXT NULL COMMENT '응답 prdt_type_cd',
    rsp_shtn_pdno TEXT NULL COMMENT '응답 shtn_pdno',
    rsp_prdt_name TEXT NULL COMMENT '응답 prdt_name',
    rsp_cblc_qty TEXT NULL COMMENT '응답 cblc_qty',
    rsp_last_alct_qty TEXT NULL COMMENT '응답 last_alct_qty',
    rsp_excs_alct_qty TEXT NULL COMMENT '응답 excs_alct_qty',
    rsp_tot_alct_qty TEXT NULL COMMENT '응답 tot_alct_qty',
    rsp_last_ftsk_qty TEXT NULL COMMENT '응답 last_ftsk_qty',
    rsp_last_alct_amt TEXT NULL COMMENT '응답 last_alct_amt',
    rsp_last_ftsk_chgs TEXT NULL COMMENT '응답 last_ftsk_chgs',
    rsp_rdpt_prca TEXT NULL COMMENT '응답 rdpt_prca',
    rsp_dlay_int_amt TEXT NULL COMMENT '응답 dlay_int_amt',
    rsp_lstg_dt TEXT NULL COMMENT '응답 lstg_dt',
    rsp_sbsc_end_dt TEXT NULL COMMENT '응답 sbsc_end_dt',
    rsp_cash_dfrm_dt TEXT NULL COMMENT '응답 cash_dfrm_dt',
    rsp_rqst_qty TEXT NULL COMMENT '응답 rqst_qty',
    rsp_rqst_amt TEXT NULL COMMENT '응답 rqst_amt',
    rsp_rqst_dt TEXT NULL COMMENT '응답 rqst_dt',
    rsp_rfnd_dt TEXT NULL COMMENT '응답 rfnd_dt',
    rsp_rfnd_amt TEXT NULL COMMENT '응답 rfnd_amt',
    rsp_lstg_stqt TEXT NULL COMMENT '응답 lstg_stqt',
    rsp_tax_amt TEXT NULL COMMENT '응답 tax_amt',
    rsp_sbsc_unpr TEXT NULL COMMENT '응답 sbsc_unpr',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/period-rights';

-- =============================================================
-- inquire_account_balance - 투자계좌자산현황조회 (CTRP6548R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/inquire-account-balance
-- =============================================================
CREATE TABLE IF NOT EXISTS inquire_account_balance (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_inqr_dvsn_1 TEXT NULL COMMENT '요청 INQR_DVSN_1',
    req_bspr_bf_dt_aply_yn TEXT NULL COMMENT '요청 BSPR_BF_DT_APLY_YN',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_output1 TEXT NULL COMMENT '응답 Output1',
    rsp_pchs_amt TEXT NULL COMMENT '응답 pchs_amt',
    rsp_evlu_amt TEXT NULL COMMENT '응답 evlu_amt',
    rsp_evlu_pfls_amt TEXT NULL COMMENT '응답 evlu_pfls_amt',
    rsp_crdt_lnd_amt TEXT NULL COMMENT '응답 crdt_lnd_amt',
    rsp_real_nass_amt TEXT NULL COMMENT '응답 real_nass_amt',
    rsp_whol_weit_rt TEXT NULL COMMENT '응답 whol_weit_rt',
    rsp_output2 TEXT NULL COMMENT '응답 Output2',
    rsp_pchs_amt_smtl TEXT NULL COMMENT '응답 pchs_amt_smtl',
    rsp_nass_tot_amt TEXT NULL COMMENT '응답 nass_tot_amt',
    rsp_loan_amt_smtl TEXT NULL COMMENT '응답 loan_amt_smtl',
    rsp_evlu_pfls_amt_smtl TEXT NULL COMMENT '응답 evlu_pfls_amt_smtl',
    rsp_evlu_amt_smtl TEXT NULL COMMENT '응답 evlu_amt_smtl',
    rsp_tot_asst_amt TEXT NULL COMMENT '응답 tot_asst_amt',
    rsp_tot_lnda_tot_ulst_lnda TEXT NULL COMMENT '응답 tot_lnda_tot_ulst_lnda',
    rsp_cma_auto_loan_amt TEXT NULL COMMENT '응답 cma_auto_loan_amt',
    rsp_tot_mgln_amt TEXT NULL COMMENT '응답 tot_mgln_amt',
    rsp_stln_evlu_amt TEXT NULL COMMENT '응답 stln_evlu_amt',
    rsp_crdt_fncg_amt TEXT NULL COMMENT '응답 crdt_fncg_amt',
    rsp_ocl_apl_loan_amt TEXT NULL COMMENT '응답 ocl_apl_loan_amt',
    rsp_pldg_stup_amt TEXT NULL COMMENT '응답 pldg_stup_amt',
    rsp_frcr_evlu_tota TEXT NULL COMMENT '응답 frcr_evlu_tota',
    rsp_tot_dncl_amt TEXT NULL COMMENT '응답 tot_dncl_amt',
    rsp_cma_evlu_amt TEXT NULL COMMENT '응답 cma_evlu_amt',
    rsp_dncl_amt TEXT NULL COMMENT '응답 dncl_amt',
    rsp_tot_sbst_amt TEXT NULL COMMENT '응답 tot_sbst_amt',
    rsp_thdt_rcvb_amt TEXT NULL COMMENT '응답 thdt_rcvb_amt',
    rsp_ovrs_stck_evlu_amt1 TEXT NULL COMMENT '응답 ovrs_stck_evlu_amt1',
    rsp_ovrs_bond_evlu_amt TEXT NULL COMMENT '응답 ovrs_bond_evlu_amt',
    rsp_mmf_cma_mgge_loan_amt TEXT NULL COMMENT '응답 mmf_cma_mgge_loan_amt',
    rsp_sbsc_dncl_amt TEXT NULL COMMENT '응답 sbsc_dncl_amt',
    rsp_pbst_sbsc_fnds_loan_use_amt TEXT NULL COMMENT '응답 pbst_sbsc_fnds_loan_use_amt',
    rsp_etpr_crdt_grnt_loan_amt TEXT NULL COMMENT '응답 etpr_crdt_grnt_loan_amt',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/inquire-account-balance';

-- =============================================================
-- pension_inquire_deposit - 퇴직연금 예수금조회 (TTTC0506R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/pension/inquire-deposit
-- =============================================================
CREATE TABLE IF NOT EXISTS pension_inquire_deposit (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_acca_dvsn_cd TEXT NULL COMMENT '요청 ACCA_DVSN_CD',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_dnca_tota TEXT NULL COMMENT '응답 dnca_tota',
    rsp_nxdy_excc_amt TEXT NULL COMMENT '응답 nxdy_excc_amt',
    rsp_nxdy_sttl_amt TEXT NULL COMMENT '응답 nxdy_sttl_amt',
    rsp_nx2_day_sttl_amt TEXT NULL COMMENT '응답 nx2_day_sttl_amt',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/pension/inquire-deposit';

-- =============================================================
-- order_resv_rvsecncl - 주식예약주문정정취소 (CTSC0009U)
-- METHOD: POST
-- URL: /uapi/domestic-stock/v1/trading/order-resv-rvsecncl
-- =============================================================
CREATE TABLE IF NOT EXISTS order_resv_rvsecncl (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    req_ord_qty TEXT NULL COMMENT '요청 ORD_QTY',
    req_ord_unpr TEXT NULL COMMENT '요청 ORD_UNPR',
    req_sll_buy_dvsn_cd TEXT NULL COMMENT '요청 SLL_BUY_DVSN_CD',
    req_ord_dvsn_cd TEXT NULL COMMENT '요청 ORD_DVSN_CD',
    req_ord_objt_cblc_dvsn_cd TEXT NULL COMMENT '요청 ORD_OBJT_CBLC_DVSN_CD',
    req_rsvn_ord_seq TEXT NULL COMMENT '요청 RSVN_ORD_SEQ',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_msg TEXT NULL COMMENT '응답 msg',
    rsp_nrml_prcs_yn TEXT NULL COMMENT '응답 nrml_prcs_yn',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/order-resv-rvsecncl';

-- =============================================================
-- inquire_credit_psamount - 신용매수가능조회 (TTTC8909R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/inquire-credit-psamount
-- =============================================================
CREATE TABLE IF NOT EXISTS inquire_credit_psamount (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    req_ord_unpr TEXT NULL COMMENT '요청 ORD_UNPR',
    req_ord_dvsn TEXT NULL COMMENT '요청 ORD_DVSN',
    req_crdt_type TEXT NULL COMMENT '요청 CRDT_TYPE',
    req_cma_evlu_amt_icld_yn TEXT NULL COMMENT '요청 CMA_EVLU_AMT_ICLD_YN',
    req_ovrs_icld_yn TEXT NULL COMMENT '요청 OVRS_ICLD_YN',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_ord_psbl_cash TEXT NULL COMMENT '응답 ord_psbl_cash',
    rsp_ord_psbl_sbst TEXT NULL COMMENT '응답 ord_psbl_sbst',
    rsp_ruse_psbl_amt TEXT NULL COMMENT '응답 ruse_psbl_amt',
    rsp_fund_rpch_chgs TEXT NULL COMMENT '응답 fund_rpch_chgs',
    rsp_psbl_qty_calc_unpr TEXT NULL COMMENT '응답 psbl_qty_calc_unpr',
    rsp_nrcvb_buy_amt TEXT NULL COMMENT '응답 nrcvb_buy_amt',
    rsp_nrcvb_buy_qty TEXT NULL COMMENT '응답 nrcvb_buy_qty',
    rsp_max_buy_amt TEXT NULL COMMENT '응답 max_buy_amt',
    rsp_max_buy_qty TEXT NULL COMMENT '응답 max_buy_qty',
    rsp_cma_evlu_amt TEXT NULL COMMENT '응답 cma_evlu_amt',
    rsp_ovrs_re_use_amt_wcrc TEXT NULL COMMENT '응답 ovrs_re_use_amt_wcrc',
    rsp_ord_psbl_frcr_amt_wcrc TEXT NULL COMMENT '응답 ord_psbl_frcr_amt_wcrc',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/inquire-credit-psamount';

-- =============================================================
-- intgr_margin - 주식통합증거금 현황 (TTTC0869R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/intgr-margin
-- =============================================================
CREATE TABLE IF NOT EXISTS intgr_margin (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_cma_evlu_amt_icld_yn TEXT NULL COMMENT '요청 CMA_EVLU_AMT_ICLD_YN',
    req_wcrc_frcr_dvsn_cd TEXT NULL COMMENT '요청 WCRC_FRCR_DVSN_CD',
    req_fwex_ctrt_frcr_dvsn_cd TEXT NULL COMMENT '요청 FWEX_CTRT_FRCR_DVSN_CD',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_acmga_rt TEXT NULL COMMENT '응답 acmga_rt',
    rsp_acmga_pct100_aptm_rson TEXT NULL COMMENT '응답 acmga_pct100_aptm_rson',
    rsp_stck_cash_objt_amt TEXT NULL COMMENT '응답 stck_cash_objt_amt',
    rsp_stck_sbst_objt_amt TEXT NULL COMMENT '응답 stck_sbst_objt_amt',
    rsp_stck_evlu_objt_amt TEXT NULL COMMENT '응답 stck_evlu_objt_amt',
    rsp_stck_ruse_psbl_objt_amt TEXT NULL COMMENT '응답 stck_ruse_psbl_objt_amt',
    rsp_stck_fund_rpch_chgs_objt_amt TEXT NULL COMMENT '응답 stck_fund_rpch_chgs_objt_amt',
    rsp_stck_fncg_rdpt_objt_atm TEXT NULL COMMENT '응답 stck_fncg_rdpt_objt_atm',
    rsp_bond_ruse_psbl_objt_amt TEXT NULL COMMENT '응답 bond_ruse_psbl_objt_amt',
    rsp_stck_cash_use_amt TEXT NULL COMMENT '응답 stck_cash_use_amt',
    rsp_stck_sbst_use_amt TEXT NULL COMMENT '응답 stck_sbst_use_amt',
    rsp_stck_evlu_use_amt TEXT NULL COMMENT '응답 stck_evlu_use_amt',
    rsp_stck_ruse_psbl_amt_use_amt TEXT NULL COMMENT '응답 stck_ruse_psbl_amt_use_amt',
    rsp_stck_fund_rpch_chgs_use_amt TEXT NULL COMMENT '응답 stck_fund_rpch_chgs_use_amt',
    rsp_stck_fncg_rdpt_amt_use_amt TEXT NULL COMMENT '응답 stck_fncg_rdpt_amt_use_amt',
    rsp_bond_ruse_psbl_amt_use_amt TEXT NULL COMMENT '응답 bond_ruse_psbl_amt_use_amt',
    rsp_stck_cash_ord_psbl_amt TEXT NULL COMMENT '응답 stck_cash_ord_psbl_amt',
    rsp_stck_sbst_ord_psbl_amt TEXT NULL COMMENT '응답 stck_sbst_ord_psbl_amt',
    rsp_stck_evlu_ord_psbl_amt TEXT NULL COMMENT '응답 stck_evlu_ord_psbl_amt',
    rsp_stck_ruse_psbl_ord_psbl_amt TEXT NULL COMMENT '응답 stck_ruse_psbl_ord_psbl_amt',
    rsp_stck_fund_rpch_ord_psbl_amt TEXT NULL COMMENT '응답 stck_fund_rpch_ord_psbl_amt',
    rsp_bond_ruse_psbl_ord_psbl_amt TEXT NULL COMMENT '응답 bond_ruse_psbl_ord_psbl_amt',
    rsp_rcvb_amt TEXT NULL COMMENT '응답 rcvb_amt',
    rsp_stck_loan_grta_ruse_psbl_amt TEXT NULL COMMENT '응답 stck_loan_grta_ruse_psbl_amt',
    rsp_stck_cash20_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_cash20_max_ord_psbl_amt',
    rsp_stck_cash30_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_cash30_max_ord_psbl_amt',
    rsp_stck_cash40_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_cash40_max_ord_psbl_amt',
    rsp_stck_cash50_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_cash50_max_ord_psbl_amt',
    rsp_stck_cash60_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_cash60_max_ord_psbl_amt',
    rsp_stck_cash100_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_cash100_max_ord_psbl_amt',
    rsp_stck_rsip100_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_rsip100_max_ord_psbl_amt',
    rsp_bond_max_ord_psbl_amt TEXT NULL COMMENT '응답 bond_max_ord_psbl_amt',
    rsp_stck_fncg45_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_fncg45_max_ord_psbl_amt',
    rsp_stck_fncg50_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_fncg50_max_ord_psbl_amt',
    rsp_stck_fncg60_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_fncg60_max_ord_psbl_amt',
    rsp_stck_fncg70_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_fncg70_max_ord_psbl_amt',
    rsp_stck_stln_max_ord_psbl_amt TEXT NULL COMMENT '응답 stck_stln_max_ord_psbl_amt',
    rsp_lmt_amt TEXT NULL COMMENT '응답 lmt_amt',
    rsp_ovrs_stck_itgr_mgna_dvsn_name TEXT NULL COMMENT '응답 ovrs_stck_itgr_mgna_dvsn_name',
    rsp_usd_objt_amt TEXT NULL COMMENT '응답 usd_objt_amt',
    rsp_usd_use_amt TEXT NULL COMMENT '응답 usd_use_amt',
    rsp_usd_ord_psbl_amt TEXT NULL COMMENT '응답 usd_ord_psbl_amt',
    rsp_hkd_objt_amt TEXT NULL COMMENT '응답 hkd_objt_amt',
    rsp_hkd_use_amt TEXT NULL COMMENT '응답 hkd_use_amt',
    rsp_hkd_ord_psbl_amt TEXT NULL COMMENT '응답 hkd_ord_psbl_amt',
    rsp_jpy_objt_amt TEXT NULL COMMENT '응답 jpy_objt_amt',
    rsp_jpy_use_amt TEXT NULL COMMENT '응답 jpy_use_amt',
    rsp_jpy_ord_psbl_amt TEXT NULL COMMENT '응답 jpy_ord_psbl_amt',
    rsp_cny_objt_amt TEXT NULL COMMENT '응답 cny_objt_amt',
    rsp_cny_use_amt TEXT NULL COMMENT '응답 cny_use_amt',
    rsp_cny_ord_psbl_amt TEXT NULL COMMENT '응답 cny_ord_psbl_amt',
    rsp_usd_ruse_objt_amt TEXT NULL COMMENT '응답 usd_ruse_objt_amt',
    rsp_usd_ruse_amt TEXT NULL COMMENT '응답 usd_ruse_amt',
    rsp_usd_ruse_ord_psbl_amt TEXT NULL COMMENT '응답 usd_ruse_ord_psbl_amt',
    rsp_hkd_ruse_objt_amt TEXT NULL COMMENT '응답 hkd_ruse_objt_amt',
    rsp_hkd_ruse_amt TEXT NULL COMMENT '응답 hkd_ruse_amt',
    rsp_hkd_ruse_ord_psbl_amt TEXT NULL COMMENT '응답 hkd_ruse_ord_psbl_amt',
    rsp_jpy_ruse_objt_amt TEXT NULL COMMENT '응답 jpy_ruse_objt_amt',
    rsp_jpy_ruse_amt TEXT NULL COMMENT '응답 jpy_ruse_amt',
    rsp_jpy_ruse_ord_psbl_amt TEXT NULL COMMENT '응답 jpy_ruse_ord_psbl_amt',
    rsp_cny_ruse_objt_amt TEXT NULL COMMENT '응답 cny_ruse_objt_amt',
    rsp_cny_ruse_amt TEXT NULL COMMENT '응답 cny_ruse_amt',
    rsp_cny_ruse_ord_psbl_amt TEXT NULL COMMENT '응답 cny_ruse_ord_psbl_amt',
    rsp_usd_gnrl_ord_psbl_amt TEXT NULL COMMENT '응답 usd_gnrl_ord_psbl_amt',
    rsp_usd_itgr_ord_psbl_amt TEXT NULL COMMENT '응답 usd_itgr_ord_psbl_amt',
    rsp_hkd_gnrl_ord_psbl_amt TEXT NULL COMMENT '응답 hkd_gnrl_ord_psbl_amt',
    rsp_hkd_itgr_ord_psbl_amt TEXT NULL COMMENT '응답 hkd_itgr_ord_psbl_amt',
    rsp_jpy_gnrl_ord_psbl_amt TEXT NULL COMMENT '응답 jpy_gnrl_ord_psbl_amt',
    rsp_jpy_itgr_ord_psbl_amt TEXT NULL COMMENT '응답 jpy_itgr_ord_psbl_amt',
    rsp_cny_gnrl_ord_psbl_amt TEXT NULL COMMENT '응답 cny_gnrl_ord_psbl_amt',
    rsp_cny_itgr_ord_psbl_amt TEXT NULL COMMENT '응답 cny_itgr_ord_psbl_amt',
    rsp_stck_itgr_cash20_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_cash20_ord_psbl_amt',
    rsp_stck_itgr_cash30_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_cash30_ord_psbl_amt',
    rsp_stck_itgr_cash40_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_cash40_ord_psbl_amt',
    rsp_stck_itgr_cash50_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_cash50_ord_psbl_amt',
    rsp_stck_itgr_cash60_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_cash60_ord_psbl_amt',
    rsp_stck_itgr_cash100_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_cash100_ord_psbl_amt',
    rsp_stck_itgr_100_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_100_ord_psbl_amt',
    rsp_stck_itgr_fncg45_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_fncg45_ord_psbl_amt',
    rsp_stck_itgr_fncg50_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_fncg50_ord_psbl_amt',
    rsp_stck_itgr_fncg60_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_fncg60_ord_psbl_amt',
    rsp_stck_itgr_fncg70_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_fncg70_ord_psbl_amt',
    rsp_stck_itgr_stln_ord_psbl_amt TEXT NULL COMMENT '응답 stck_itgr_stln_ord_psbl_amt',
    rsp_bond_itgr_ord_psbl_amt TEXT NULL COMMENT '응답 bond_itgr_ord_psbl_amt',
    rsp_stck_cash_ovrs_use_amt TEXT NULL COMMENT '응답 stck_cash_ovrs_use_amt',
    rsp_stck_sbst_ovrs_use_amt TEXT NULL COMMENT '응답 stck_sbst_ovrs_use_amt',
    rsp_stck_evlu_ovrs_use_amt TEXT NULL COMMENT '응답 stck_evlu_ovrs_use_amt',
    rsp_stck_re_use_amt_ovrs_use_amt TEXT NULL COMMENT '응답 stck_re_use_amt_ovrs_use_amt',
    rsp_stck_fund_rpch_ovrs_use_amt TEXT NULL COMMENT '응답 stck_fund_rpch_ovrs_use_amt',
    rsp_stck_fncg_rdpt_ovrs_use_amt TEXT NULL COMMENT '응답 stck_fncg_rdpt_ovrs_use_amt',
    rsp_bond_re_use_ovrs_use_amt TEXT NULL COMMENT '응답 bond_re_use_ovrs_use_amt',
    rsp_usd_oth_mket_use_amt TEXT NULL COMMENT '응답 usd_oth_mket_use_amt',
    rsp_jpy_oth_mket_use_amt TEXT NULL COMMENT '응답 jpy_oth_mket_use_amt',
    rsp_cny_oth_mket_use_amt TEXT NULL COMMENT '응답 cny_oth_mket_use_amt',
    rsp_hkd_oth_mket_use_amt TEXT NULL COMMENT '응답 hkd_oth_mket_use_amt',
    rsp_usd_re_use_oth_mket_use_amt TEXT NULL COMMENT '응답 usd_re_use_oth_mket_use_amt',
    rsp_jpy_re_use_oth_mket_use_amt TEXT NULL COMMENT '응답 jpy_re_use_oth_mket_use_amt',
    rsp_cny_re_use_oth_mket_use_amt TEXT NULL COMMENT '응답 cny_re_use_oth_mket_use_amt',
    rsp_hkd_re_use_oth_mket_use_amt TEXT NULL COMMENT '응답 hkd_re_use_oth_mket_use_amt',
    rsp_hgkg_cny_re_use_amt TEXT NULL COMMENT '응답 hgkg_cny_re_use_amt',
    rsp_usd_frst_bltn_exrt TEXT NULL COMMENT '응답 usd_frst_bltn_exrt',
    rsp_hkd_frst_bltn_exrt TEXT NULL COMMENT '응답 hkd_frst_bltn_exrt',
    rsp_jpy_frst_bltn_exrt TEXT NULL COMMENT '응답 jpy_frst_bltn_exrt',
    rsp_cny_frst_bltn_exrt TEXT NULL COMMENT '응답 cny_frst_bltn_exrt',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/intgr-margin';

-- =============================================================
-- pension_inquire_daily_ccld - 퇴직연금 미체결내역 (TTTC2201R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/pension/inquire-daily-ccld
-- =============================================================
CREATE TABLE IF NOT EXISTS pension_inquire_daily_ccld (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_user_dvsn_cd TEXT NULL COMMENT '요청 USER_DVSN_CD',
    req_sll_buy_dvsn_cd TEXT NULL COMMENT '요청 SLL_BUY_DVSN_CD',
    req_ccld_nccs_dvsn TEXT NULL COMMENT '요청 CCLD_NCCS_DVSN',
    req_inqr_dvsn_3 TEXT NULL COMMENT '요청 INQR_DVSN_3',
    req_ctx_area_fk100 TEXT NULL COMMENT '요청 CTX_AREA_FK100',
    req_ctx_area_nk100 TEXT NULL COMMENT '요청 CTX_AREA_NK100',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_ord_gno_brno TEXT NULL COMMENT '응답 ord_gno_brno',
    rsp_sll_buy_dvsn_cd TEXT NULL COMMENT '응답 sll_buy_dvsn_cd',
    rsp_trad_dvsn_name TEXT NULL COMMENT '응답 trad_dvsn_name',
    rsp_odno TEXT NULL COMMENT '응답 odno',
    rsp_pdno TEXT NULL COMMENT '응답 pdno',
    rsp_prdt_name TEXT NULL COMMENT '응답 prdt_name',
    rsp_ord_unpr TEXT NULL COMMENT '응답 ord_unpr',
    rsp_ord_qty TEXT NULL COMMENT '응답 ord_qty',
    rsp_tot_ccld_qty TEXT NULL COMMENT '응답 tot_ccld_qty',
    rsp_nccs_qty TEXT NULL COMMENT '응답 nccs_qty',
    rsp_ord_dvsn_cd TEXT NULL COMMENT '응답 ord_dvsn_cd',
    rsp_ord_dvsn_name TEXT NULL COMMENT '응답 ord_dvsn_name',
    rsp_orgn_odno TEXT NULL COMMENT '응답 orgn_odno',
    rsp_ord_tmd TEXT NULL COMMENT '응답 ord_tmd',
    rsp_objt_cust_dvsn_name TEXT NULL COMMENT '응답 objt_cust_dvsn_name',
    rsp_pchs_avg_pric TEXT NULL COMMENT '응답 pchs_avg_pric',
    rsp_stpm_cndt_pric TEXT NULL COMMENT '응답 stpm_cndt_pric',
    rsp_stpm_efct_occr_dtmd TEXT NULL COMMENT '응답 stpm_efct_occr_dtmd',
    rsp_stpm_efct_occr_yn TEXT NULL COMMENT '응답 stpm_efct_occr_yn',
    rsp_excg_id_dvsn_cd TEXT NULL COMMENT '응답 excg_id_dvsn_cd',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/pension/inquire-daily-ccld';

-- =============================================================
-- inquire_period_trade_profit - 기간별매매손익현황조회 (TTTC8715R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/inquire-period-trade-profit
-- =============================================================
CREATE TABLE IF NOT EXISTS inquire_period_trade_profit (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_sort_dvsn TEXT NULL COMMENT '요청 SORT_DVSN',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    req_inqr_strt_dt TEXT NULL COMMENT '요청 INQR_STRT_DT',
    req_inqr_end_dt TEXT NULL COMMENT '요청 INQR_END_DT',
    req_ctx_area_nk100 TEXT NULL COMMENT '요청 CTX_AREA_NK100',
    req_cblc_dvsn TEXT NULL COMMENT '요청 CBLC_DVSN',
    req_ctx_area_fk100 TEXT NULL COMMENT '요청 CTX_AREA_FK100',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_ctx_area_nk100 TEXT NULL COMMENT '응답 ctx_area_nk100',
    rsp_ctx_area_fk100 TEXT NULL COMMENT '응답 ctx_area_fk100',
    rsp_trad_dt TEXT NULL COMMENT '응답 trad_dt',
    rsp_pdno TEXT NULL COMMENT '응답 pdno',
    rsp_prdt_name TEXT NULL COMMENT '응답 prdt_name',
    rsp_trad_dvsn_name TEXT NULL COMMENT '응답 trad_dvsn_name',
    rsp_loan_dt TEXT NULL COMMENT '응답 loan_dt',
    rsp_hldg_qty TEXT NULL COMMENT '응답 hldg_qty',
    rsp_pchs_unpr TEXT NULL COMMENT '응답 pchs_unpr',
    rsp_buy_qty TEXT NULL COMMENT '응답 buy_qty',
    rsp_buy_amt TEXT NULL COMMENT '응답 buy_amt',
    rsp_sll_pric TEXT NULL COMMENT '응답 sll_pric',
    rsp_sll_qty TEXT NULL COMMENT '응답 sll_qty',
    rsp_sll_amt TEXT NULL COMMENT '응답 sll_amt',
    rsp_rlzt_pfls TEXT NULL COMMENT '응답 rlzt_pfls',
    rsp_pfls_rt TEXT NULL COMMENT '응답 pfls_rt',
    rsp_fee TEXT NULL COMMENT '응답 fee',
    rsp_tl_tax TEXT NULL COMMENT '응답 tl_tax',
    rsp_loan_int TEXT NULL COMMENT '응답 loan_int',
    rsp_sll_qty_smtl TEXT NULL COMMENT '응답 sll_qty_smtl',
    rsp_sll_tr_amt_smtl TEXT NULL COMMENT '응답 sll_tr_amt_smtl',
    rsp_sll_fee_smtl TEXT NULL COMMENT '응답 sll_fee_smtl',
    rsp_sll_tltx_smtl TEXT NULL COMMENT '응답 sll_tltx_smtl',
    rsp_sll_excc_amt_smtl TEXT NULL COMMENT '응답 sll_excc_amt_smtl',
    rsp_buyqty_smtl TEXT NULL COMMENT '응답 buyqty_smtl',
    rsp_buy_tr_amt_smtl TEXT NULL COMMENT '응답 buy_tr_amt_smtl',
    rsp_buy_fee_smtl TEXT NULL COMMENT '응답 buy_fee_smtl',
    rsp_buy_tax_smtl TEXT NULL COMMENT '응답 buy_tax_smtl',
    rsp_buy_excc_amt_smtl TEXT NULL COMMENT '응답 buy_excc_amt_smtl',
    rsp_tot_qty TEXT NULL COMMENT '응답 tot_qty',
    rsp_tot_tr_amt TEXT NULL COMMENT '응답 tot_tr_amt',
    rsp_tot_fee TEXT NULL COMMENT '응답 tot_fee',
    rsp_tot_tltx TEXT NULL COMMENT '응답 tot_tltx',
    rsp_tot_excc_amt TEXT NULL COMMENT '응답 tot_excc_amt',
    rsp_tot_rlzt_pfls TEXT NULL COMMENT '응답 tot_rlzt_pfls',
    rsp_tot_pftrt TEXT NULL COMMENT '응답 tot_pftrt',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/inquire-period-trade-profit';

-- =============================================================
-- order_rvsecncl - 주식주문(정정취소) (TTTC0013U)
-- METHOD: POST
-- URL: /uapi/domestic-stock/v1/trading/order-rvsecncl
-- =============================================================
CREATE TABLE IF NOT EXISTS order_rvsecncl (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_krx_fwdg_ord_orgno TEXT NULL COMMENT '요청 KRX_FWDG_ORD_ORGNO',
    req_orgn_odno TEXT NULL COMMENT '요청 ORGN_ODNO',
    req_ord_dvsn TEXT NULL COMMENT '요청 ORD_DVSN',
    req_rvse_cncl_dvsn_cd TEXT NULL COMMENT '요청 RVSE_CNCL_DVSN_CD',
    req_ord_qty TEXT NULL COMMENT '요청 ORD_QTY',
    req_ord_unpr TEXT NULL COMMENT '요청 ORD_UNPR',
    req_qty_all_ord_yn TEXT NULL COMMENT '요청 QTY_ALL_ORD_YN',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_krx_fwdg_ord_orgno TEXT NULL COMMENT '응답 krx_fwdg_ord_orgno',
    rsp_odno TEXT NULL COMMENT '응답 odno',
    rsp_ord_tmd TEXT NULL COMMENT '응답 ord_tmd',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/order-rvsecncl';

-- =============================================================
-- order_resv_ccnl - 주식예약주문조회 (CTSC0004R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/order-resv-ccnl
-- =============================================================
CREATE TABLE IF NOT EXISTS order_resv_ccnl (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_rsvn_ord_ord_dt TEXT NULL COMMENT '요청 RSVN_ORD_ORD_DT',
    req_rsvn_ord_end_dt TEXT NULL COMMENT '요청 RSVN_ORD_END_DT',
    req_rsvn_ord_seq TEXT NULL COMMENT '요청 RSVN_ORD_SEQ',
    req_tmnl_mdia_kind_cd TEXT NULL COMMENT '요청 TMNL_MDIA_KIND_CD',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_prcs_dvsn_cd TEXT NULL COMMENT '요청 PRCS_DVSN_CD',
    req_cncl_yn TEXT NULL COMMENT '요청 CNCL_YN',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    req_sll_buy_dvsn_cd TEXT NULL COMMENT '요청 SLL_BUY_DVSN_CD',
    req_ctx_area_fk200 TEXT NULL COMMENT '요청 CTX_AREA_FK200',
    req_ctx_area_nk200 TEXT NULL COMMENT '요청 CTX_AREA_NK200',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_rsvn_ord_seq TEXT NULL COMMENT '응답 rsvn_ord_seq',
    rsp_rsvn_ord_ord_dt TEXT NULL COMMENT '응답 rsvn_ord_ord_dt',
    rsp_rsvn_ord_rcit_dt TEXT NULL COMMENT '응답 rsvn_ord_rcit_dt',
    rsp_pdno TEXT NULL COMMENT '응답 pdno',
    rsp_ord_dvsn_cd TEXT NULL COMMENT '응답 ord_dvsn_cd',
    rsp_ord_rsvn_qty TEXT NULL COMMENT '응답 ord_rsvn_qty',
    rsp_tot_ccld_qty TEXT NULL COMMENT '응답 tot_ccld_qty',
    rsp_cncl_ord_dt TEXT NULL COMMENT '응답 cncl_ord_dt',
    rsp_ord_tmd TEXT NULL COMMENT '응답 ord_tmd',
    rsp_ctac_tlno TEXT NULL COMMENT '응답 ctac_tlno',
    rsp_rjct_rson2 TEXT NULL COMMENT '응답 rjct_rson2',
    rsp_odno TEXT NULL COMMENT '응답 odno',
    rsp_rsvn_ord_rcit_tmd TEXT NULL COMMENT '응답 rsvn_ord_rcit_tmd',
    rsp_kor_item_shtn_name TEXT NULL COMMENT '응답 kor_item_shtn_name',
    rsp_sll_buy_dvsn_cd TEXT NULL COMMENT '응답 sll_buy_dvsn_cd',
    rsp_ord_rsvn_unpr TEXT NULL COMMENT '응답 ord_rsvn_unpr',
    rsp_tot_ccld_amt TEXT NULL COMMENT '응답 tot_ccld_amt',
    rsp_loan_dt TEXT NULL COMMENT '응답 loan_dt',
    rsp_cncl_rcit_tmd TEXT NULL COMMENT '응답 cncl_rcit_tmd',
    rsp_prcs_rslt TEXT NULL COMMENT '응답 prcs_rslt',
    rsp_ord_dvsn_name TEXT NULL COMMENT '응답 ord_dvsn_name',
    rsp_tmnl_mdia_kind_cd TEXT NULL COMMENT '응답 tmnl_mdia_kind_cd',
    rsp_rsvn_end_dt TEXT NULL COMMENT '응답 rsvn_end_dt',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/order-resv-ccnl';

-- =============================================================
-- pension_inquire_psbl_order - 퇴직연금 매수가능조회 (TTTC0503R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/pension/inquire-psbl-order
-- =============================================================
CREATE TABLE IF NOT EXISTS pension_inquire_psbl_order (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    req_acca_dvsn_cd TEXT NULL COMMENT '요청 ACCA_DVSN_CD',
    req_cma_evlu_amt_icld_yn TEXT NULL COMMENT '요청 CMA_EVLU_AMT_ICLD_YN',
    req_ord_dvsn TEXT NULL COMMENT '요청 ORD_DVSN',
    req_ord_unpr TEXT NULL COMMENT '요청 ORD_UNPR',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_ord_psbl_cash TEXT NULL COMMENT '응답 ord_psbl_cash',
    rsp_ruse_psbl_amt TEXT NULL COMMENT '응답 ruse_psbl_amt',
    rsp_psbl_qty_calc_unpr TEXT NULL COMMENT '응답 psbl_qty_calc_unpr',
    rsp_max_buy_amt TEXT NULL COMMENT '응답 max_buy_amt',
    rsp_max_buy_qty TEXT NULL COMMENT '응답 max_buy_qty',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/pension/inquire-psbl-order';

-- =============================================================
-- inquire_balance - 주식잔고조회 (TTTC8434R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/inquire-balance
-- =============================================================
CREATE TABLE IF NOT EXISTS inquire_balance (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_afhr_flpr_yn TEXT NULL COMMENT '요청 AFHR_FLPR_YN',
    req_inqr_dvsn TEXT NULL COMMENT '요청 INQR_DVSN',
    req_unpr_dvsn TEXT NULL COMMENT '요청 UNPR_DVSN',
    req_fund_sttl_icld_yn TEXT NULL COMMENT '요청 FUND_STTL_ICLD_YN',
    req_fncg_amt_auto_rdpt_yn TEXT NULL COMMENT '요청 FNCG_AMT_AUTO_RDPT_YN',
    req_prcs_dvsn TEXT NULL COMMENT '요청 PRCS_DVSN',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_ctx_area_fk100 TEXT NULL COMMENT '응답 ctx_area_fk100',
    rsp_ctx_area_nk100 TEXT NULL COMMENT '응답 ctx_area_nk100',
    rsp_pdno TEXT NULL COMMENT '응답 pdno',
    rsp_prdt_name TEXT NULL COMMENT '응답 prdt_name',
    rsp_trad_dvsn_name TEXT NULL COMMENT '응답 trad_dvsn_name',
    rsp_bfdy_buy_qty TEXT NULL COMMENT '응답 bfdy_buy_qty',
    rsp_bfdy_sll_qty TEXT NULL COMMENT '응답 bfdy_sll_qty',
    rsp_thdt_buyqty TEXT NULL COMMENT '응답 thdt_buyqty',
    rsp_thdt_sll_qty TEXT NULL COMMENT '응답 thdt_sll_qty',
    rsp_hldg_qty TEXT NULL COMMENT '응답 hldg_qty',
    rsp_ord_psbl_qty TEXT NULL COMMENT '응답 ord_psbl_qty',
    rsp_pchs_avg_pric TEXT NULL COMMENT '응답 pchs_avg_pric',
    rsp_pchs_amt TEXT NULL COMMENT '응답 pchs_amt',
    rsp_prpr TEXT NULL COMMENT '응답 prpr',
    rsp_evlu_amt TEXT NULL COMMENT '응답 evlu_amt',
    rsp_evlu_pfls_amt TEXT NULL COMMENT '응답 evlu_pfls_amt',
    rsp_evlu_pfls_rt TEXT NULL COMMENT '응답 evlu_pfls_rt',
    rsp_evlu_erng_rt TEXT NULL COMMENT '응답 evlu_erng_rt',
    rsp_loan_dt TEXT NULL COMMENT '응답 loan_dt',
    rsp_loan_amt TEXT NULL COMMENT '응답 loan_amt',
    rsp_stln_slng_chgs TEXT NULL COMMENT '응답 stln_slng_chgs',
    rsp_expd_dt TEXT NULL COMMENT '응답 expd_dt',
    rsp_fltt_rt TEXT NULL COMMENT '응답 fltt_rt',
    rsp_bfdy_cprs_icdc TEXT NULL COMMENT '응답 bfdy_cprs_icdc',
    rsp_item_mgna_rt_name TEXT NULL COMMENT '응답 item_mgna_rt_name',
    rsp_grta_rt_name TEXT NULL COMMENT '응답 grta_rt_name',
    rsp_sbst_pric TEXT NULL COMMENT '응답 sbst_pric',
    rsp_stck_loan_unpr TEXT NULL COMMENT '응답 stck_loan_unpr',
    rsp_dnca_tot_amt TEXT NULL COMMENT '응답 dnca_tot_amt',
    rsp_nxdy_excc_amt TEXT NULL COMMENT '응답 nxdy_excc_amt',
    rsp_prvs_rcdl_excc_amt TEXT NULL COMMENT '응답 prvs_rcdl_excc_amt',
    rsp_cma_evlu_amt TEXT NULL COMMENT '응답 cma_evlu_amt',
    rsp_bfdy_buy_amt TEXT NULL COMMENT '응답 bfdy_buy_amt',
    rsp_thdt_buy_amt TEXT NULL COMMENT '응답 thdt_buy_amt',
    rsp_nxdy_auto_rdpt_amt TEXT NULL COMMENT '응답 nxdy_auto_rdpt_amt',
    rsp_bfdy_sll_amt TEXT NULL COMMENT '응답 bfdy_sll_amt',
    rsp_thdt_sll_amt TEXT NULL COMMENT '응답 thdt_sll_amt',
    rsp_d2_auto_rdpt_amt TEXT NULL COMMENT '응답 d2_auto_rdpt_amt',
    rsp_bfdy_tlex_amt TEXT NULL COMMENT '응답 bfdy_tlex_amt',
    rsp_thdt_tlex_amt TEXT NULL COMMENT '응답 thdt_tlex_amt',
    rsp_tot_loan_amt TEXT NULL COMMENT '응답 tot_loan_amt',
    rsp_scts_evlu_amt TEXT NULL COMMENT '응답 scts_evlu_amt',
    rsp_tot_evlu_amt TEXT NULL COMMENT '응답 tot_evlu_amt',
    rsp_nass_amt TEXT NULL COMMENT '응답 nass_amt',
    rsp_fncg_gld_auto_rdpt_yn TEXT NULL COMMENT '응답 fncg_gld_auto_rdpt_yn',
    rsp_pchs_amt_smtl_amt TEXT NULL COMMENT '응답 pchs_amt_smtl_amt',
    rsp_evlu_amt_smtl_amt TEXT NULL COMMENT '응답 evlu_amt_smtl_amt',
    rsp_evlu_pfls_smtl_amt TEXT NULL COMMENT '응답 evlu_pfls_smtl_amt',
    rsp_tot_stln_slng_chgs TEXT NULL COMMENT '응답 tot_stln_slng_chgs',
    rsp_bfdy_tot_asst_evlu_amt TEXT NULL COMMENT '응답 bfdy_tot_asst_evlu_amt',
    rsp_asst_icdc_amt TEXT NULL COMMENT '응답 asst_icdc_amt',
    rsp_asst_icdc_erng_rt TEXT NULL COMMENT '응답 asst_icdc_erng_rt',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/inquire-balance';

-- =============================================================
-- pension_inquire_present_balance - 퇴직연금 체결기준잔고 (TTTC2202R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/pension/inquire-present-balance
-- =============================================================
CREATE TABLE IF NOT EXISTS pension_inquire_present_balance (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_user_dvsn_cd TEXT NULL COMMENT '요청 USER_DVSN_CD',
    req_ctx_area_fk100 TEXT NULL COMMENT '요청 CTX_AREA_FK100',
    req_ctx_area_nk100 TEXT NULL COMMENT '요청 CTX_AREA_NK100',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_cblc_dvsn TEXT NULL COMMENT '응답 cblc_dvsn',
    rsp_cblc_dvsn_name TEXT NULL COMMENT '응답 cblc_dvsn_name',
    rsp_pdno TEXT NULL COMMENT '응답 pdno',
    rsp_prdt_name TEXT NULL COMMENT '응답 prdt_name',
    rsp_hldg_qty TEXT NULL COMMENT '응답 hldg_qty',
    rsp_slpsb_qty TEXT NULL COMMENT '응답 slpsb_qty',
    rsp_pchs_avg_pric TEXT NULL COMMENT '응답 pchs_avg_pric',
    rsp_evlu_pfls_amt TEXT NULL COMMENT '응답 evlu_pfls_amt',
    rsp_evlu_pfls_rt TEXT NULL COMMENT '응답 evlu_pfls_rt',
    rsp_prpr TEXT NULL COMMENT '응답 prpr',
    rsp_evlu_amt TEXT NULL COMMENT '응답 evlu_amt',
    rsp_pchs_amt TEXT NULL COMMENT '응답 pchs_amt',
    rsp_cblc_weit TEXT NULL COMMENT '응답 cblc_weit',
    rsp_pchs_amt_smtl_amt TEXT NULL COMMENT '응답 pchs_amt_smtl_amt',
    rsp_evlu_amt_smtl_amt TEXT NULL COMMENT '응답 evlu_amt_smtl_amt',
    rsp_evlu_pfls_smtl_amt TEXT NULL COMMENT '응답 evlu_pfls_smtl_amt',
    rsp_trad_pfls_smtl TEXT NULL COMMENT '응답 trad_pfls_smtl',
    rsp_thdt_tot_pfls_amt TEXT NULL COMMENT '응답 thdt_tot_pfls_amt',
    rsp_pftrt TEXT NULL COMMENT '응답 pftrt',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/pension/inquire-present-balance';

-- =============================================================
-- inquire_psbl_order - 매수가능조회 (TTTC8908R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/inquire-psbl-order
-- =============================================================
CREATE TABLE IF NOT EXISTS inquire_psbl_order (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    req_ord_unpr TEXT NULL COMMENT '요청 ORD_UNPR',
    req_ord_dvsn TEXT NULL COMMENT '요청 ORD_DVSN',
    req_cma_evlu_amt_icld_yn TEXT NULL COMMENT '요청 CMA_EVLU_AMT_ICLD_YN',
    req_ovrs_icld_yn TEXT NULL COMMENT '요청 OVRS_ICLD_YN',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_ord_psbl_cash TEXT NULL COMMENT '응답 ord_psbl_cash',
    rsp_ord_psbl_sbst TEXT NULL COMMENT '응답 ord_psbl_sbst',
    rsp_ruse_psbl_amt TEXT NULL COMMENT '응답 ruse_psbl_amt',
    rsp_fund_rpch_chgs TEXT NULL COMMENT '응답 fund_rpch_chgs',
    rsp_psbl_qty_calc_unpr TEXT NULL COMMENT '응답 psbl_qty_calc_unpr',
    rsp_nrcvb_buy_amt TEXT NULL COMMENT '응답 nrcvb_buy_amt',
    rsp_nrcvb_buy_qty TEXT NULL COMMENT '응답 nrcvb_buy_qty',
    rsp_max_buy_amt TEXT NULL COMMENT '응답 max_buy_amt',
    rsp_max_buy_qty TEXT NULL COMMENT '응답 max_buy_qty',
    rsp_cma_evlu_amt TEXT NULL COMMENT '응답 cma_evlu_amt',
    rsp_ovrs_re_use_amt_wcrc TEXT NULL COMMENT '응답 ovrs_re_use_amt_wcrc',
    rsp_ord_psbl_frcr_amt_wcrc TEXT NULL COMMENT '응답 ord_psbl_frcr_amt_wcrc',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/inquire-psbl-order';

-- =============================================================
-- inquire_period_profit - 기간별손익일별합산조회 (TTTC8708R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/inquire-period-profit
-- =============================================================
CREATE TABLE IF NOT EXISTS inquire_period_profit (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_inqr_strt_dt TEXT NULL COMMENT '요청 INQR_STRT_DT',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    req_ctx_area_nk100 TEXT NULL COMMENT '요청 CTX_AREA_NK100',
    req_inqr_end_dt TEXT NULL COMMENT '요청 INQR_END_DT',
    req_sort_dvsn TEXT NULL COMMENT '요청 SORT_DVSN',
    req_inqr_dvsn TEXT NULL COMMENT '요청 INQR_DVSN',
    req_cblc_dvsn TEXT NULL COMMENT '요청 CBLC_DVSN',
    req_ctx_area_fk100 TEXT NULL COMMENT '요청 CTX_AREA_FK100',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_trad_dt TEXT NULL COMMENT '응답 trad_dt',
    rsp_buy_amt TEXT NULL COMMENT '응답 buy_amt',
    rsp_sll_amt TEXT NULL COMMENT '응답 sll_amt',
    rsp_rlzt_pfls TEXT NULL COMMENT '응답 rlzt_pfls',
    rsp_fee TEXT NULL COMMENT '응답 fee',
    rsp_loan_int TEXT NULL COMMENT '응답 loan_int',
    rsp_tl_tax TEXT NULL COMMENT '응답 tl_tax',
    rsp_pfls_rt TEXT NULL COMMENT '응답 pfls_rt',
    rsp_sll_qty1 TEXT NULL COMMENT '응답 sll_qty1',
    rsp_buy_qty1 TEXT NULL COMMENT '응답 buy_qty1',
    rsp_sll_qty_smtl TEXT NULL COMMENT '응답 sll_qty_smtl',
    rsp_sll_tr_amt_smtl TEXT NULL COMMENT '응답 sll_tr_amt_smtl',
    rsp_sll_fee_smtl TEXT NULL COMMENT '응답 sll_fee_smtl',
    rsp_sll_tltx_smtl TEXT NULL COMMENT '응답 sll_tltx_smtl',
    rsp_sll_excc_amt_smtl TEXT NULL COMMENT '응답 sll_excc_amt_smtl',
    rsp_buy_qty_smtl TEXT NULL COMMENT '응답 buy_qty_smtl',
    rsp_buy_tr_amt_smtl TEXT NULL COMMENT '응답 buy_tr_amt_smtl',
    rsp_buy_fee_smtl TEXT NULL COMMENT '응답 buy_fee_smtl',
    rsp_buy_tax_smtl TEXT NULL COMMENT '응답 buy_tax_smtl',
    rsp_buy_excc_amt_smtl TEXT NULL COMMENT '응답 buy_excc_amt_smtl',
    rsp_tot_qty TEXT NULL COMMENT '응답 tot_qty',
    rsp_tot_tr_amt TEXT NULL COMMENT '응답 tot_tr_amt',
    rsp_tot_fee TEXT NULL COMMENT '응답 tot_fee',
    rsp_tot_tltx TEXT NULL COMMENT '응답 tot_tltx',
    rsp_tot_excc_amt TEXT NULL COMMENT '응답 tot_excc_amt',
    rsp_tot_rlzt_pfls TEXT NULL COMMENT '응답 tot_rlzt_pfls',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/inquire-period-profit';

-- =============================================================
-- order_cash - 주식주문(현금) (TTTC0011U)
-- METHOD: POST
-- URL: /uapi/domestic-stock/v1/trading/order-cash
-- =============================================================
CREATE TABLE IF NOT EXISTS order_cash (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    req_ord_dvsn TEXT NULL COMMENT '요청 ORD_DVSN',
    req_ord_qty TEXT NULL COMMENT '요청 ORD_QTY',
    req_ord_unpr TEXT NULL COMMENT '요청 ORD_UNPR',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_krx_fwdg_ord_orgno TEXT NULL COMMENT '응답 KRX_FWDG_ORD_ORGNO',
    rsp_odno TEXT NULL COMMENT '응답 ODNO',
    rsp_ord_tmd TEXT NULL COMMENT '응답 ORD_TMD',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/order-cash';

-- =============================================================
-- inquire_psbl_sell - 매도가능수량조회 (TTTC8408R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/inquire-psbl-sell
-- =============================================================
CREATE TABLE IF NOT EXISTS inquire_psbl_sell (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_pdno TEXT NULL COMMENT '응답 pdno',
    rsp_prdt_name TEXT NULL COMMENT '응답 prdt_name',
    rsp_buy_qty TEXT NULL COMMENT '응답 buy_qty',
    rsp_sll_qty TEXT NULL COMMENT '응답 sll_qty',
    rsp_cblc_qty TEXT NULL COMMENT '응답 cblc_qty',
    rsp_nsvg_qty TEXT NULL COMMENT '응답 nsvg_qty',
    rsp_ord_psbl_qty TEXT NULL COMMENT '응답 ord_psbl_qty',
    rsp_pchs_avg_pric TEXT NULL COMMENT '응답 pchs_avg_pric',
    rsp_pchs_amt TEXT NULL COMMENT '응답 pchs_amt',
    rsp_now_pric TEXT NULL COMMENT '응답 now_pric',
    rsp_evlu_amt TEXT NULL COMMENT '응답 evlu_amt',
    rsp_evlu_pfls_amt TEXT NULL COMMENT '응답 evlu_pfls_amt',
    rsp_evlu_pfls_rt TEXT NULL COMMENT '응답 evlu_pfls_rt',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/inquire-psbl-sell';

-- =============================================================
-- inquire_daily_ccld - 주식일별주문체결조회 (TTTC0081R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/inquire-daily-ccld
-- =============================================================
CREATE TABLE IF NOT EXISTS inquire_daily_ccld (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_inqr_strt_dt TEXT NULL COMMENT '요청 INQR_STRT_DT',
    req_inqr_end_dt TEXT NULL COMMENT '요청 INQR_END_DT',
    req_sll_buy_dvsn_cd TEXT NULL COMMENT '요청 SLL_BUY_DVSN_CD',
    req_ord_gno_brno TEXT NULL COMMENT '요청 ORD_GNO_BRNO',
    req_ccld_dvsn TEXT NULL COMMENT '요청 CCLD_DVSN',
    req_inqr_dvsn TEXT NULL COMMENT '요청 INQR_DVSN',
    req_inqr_dvsn_1 TEXT NULL COMMENT '요청 INQR_DVSN_1',
    req_inqr_dvsn_3 TEXT NULL COMMENT '요청 INQR_DVSN_3',
    req_excg_id_dvsn_cd TEXT NULL COMMENT '요청 EXCG_ID_DVSN_CD',
    req_ctx_area_fk100 TEXT NULL COMMENT '요청 CTX_AREA_FK100',
    req_ctx_area_nk100 TEXT NULL COMMENT '요청 CTX_AREA_NK100',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_ord_dt TEXT NULL COMMENT '응답 ord_dt',
    rsp_ord_gno_brno TEXT NULL COMMENT '응답 ord_gno_brno',
    rsp_odno TEXT NULL COMMENT '응답 odno',
    rsp_orgn_odno TEXT NULL COMMENT '응답 orgn_odno',
    rsp_ord_dvsn_name TEXT NULL COMMENT '응답 ord_dvsn_name',
    rsp_sll_buy_dvsn_cd TEXT NULL COMMENT '응답 sll_buy_dvsn_cd',
    rsp_sll_buy_dvsn_cd_name TEXT NULL COMMENT '응답 sll_buy_dvsn_cd_name',
    rsp_pdno TEXT NULL COMMENT '응답 pdno',
    rsp_prdt_name TEXT NULL COMMENT '응답 prdt_name',
    rsp_ord_qty TEXT NULL COMMENT '응답 ord_qty',
    rsp_ord_unpr TEXT NULL COMMENT '응답 ord_unpr',
    rsp_ord_tmd TEXT NULL COMMENT '응답 ord_tmd',
    rsp_tot_ccld_qty TEXT NULL COMMENT '응답 tot_ccld_qty',
    rsp_avg_prvs TEXT NULL COMMENT '응답 avg_prvs',
    rsp_cncl_yn TEXT NULL COMMENT '응답 cncl_yn',
    rsp_tot_ccld_amt TEXT NULL COMMENT '응답 tot_ccld_amt',
    rsp_loan_dt TEXT NULL COMMENT '응답 loan_dt',
    rsp_ordr_empno TEXT NULL COMMENT '응답 ordr_empno',
    rsp_ord_dvsn_cd TEXT NULL COMMENT '응답 ord_dvsn_cd',
    rsp_cnc_cfrm_qty TEXT NULL COMMENT '응답 cnc_cfrm_qty',
    rsp_rmn_qty TEXT NULL COMMENT '응답 rmn_qty',
    rsp_rjct_qty TEXT NULL COMMENT '응답 rjct_qty',
    rsp_ccld_cndt_name TEXT NULL COMMENT '응답 ccld_cndt_name',
    rsp_inqr_ip_addr TEXT NULL COMMENT '응답 inqr_ip_addr',
    rsp_cpbc_ordp_ord_rcit_dvsn_cd TEXT NULL COMMENT '응답 cpbc_ordp_ord_rcit_dvsn_cd',
    rsp_cpbc_ordp_infm_mthd_dvsn_cd TEXT NULL COMMENT '응답 cpbc_ordp_infm_mthd_dvsn_cd',
    rsp_infm_tmd TEXT NULL COMMENT '응답 infm_tmd',
    rsp_ctac_tlno TEXT NULL COMMENT '응답 ctac_tlno',
    rsp_prdt_type_cd TEXT NULL COMMENT '응답 prdt_type_cd',
    rsp_excg_dvsn_cd TEXT NULL COMMENT '응답 excg_dvsn_cd',
    rsp_cpbc_ordp_mtrl_dvsn_cd TEXT NULL COMMENT '응답 cpbc_ordp_mtrl_dvsn_cd',
    rsp_ord_orgno TEXT NULL COMMENT '응답 ord_orgno',
    rsp_rsvn_ord_end_dt TEXT NULL COMMENT '응답 rsvn_ord_end_dt',
    rsp_excg_id_dvsn_cd TEXT NULL COMMENT '응답 excg_id_dvsn_Cd',
    rsp_stpm_cndt_pric TEXT NULL COMMENT '응답 stpm_cndt_pric',
    rsp_stpm_efct_occr_dtmd TEXT NULL COMMENT '응답 stpm_efct_occr_dtmd',
    rsp_tot_ord_qty TEXT NULL COMMENT '응답 tot_ord_qty',
    rsp_prsm_tlex_smtl TEXT NULL COMMENT '응답 prsm_tlex_smtl',
    rsp_pchs_avg_pric TEXT NULL COMMENT '응답 pchs_avg_pric',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/inquire-daily-ccld';

-- =============================================================
-- inquire_psbl_rvsecncl - 주식정정취소가능주문조회 (TTTC0084R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/inquire-psbl-rvsecncl
-- =============================================================
CREATE TABLE IF NOT EXISTS inquire_psbl_rvsecncl (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_ctx_area_fk100 TEXT NULL COMMENT '요청 CTX_AREA_FK100',
    req_ctx_area_nk100 TEXT NULL COMMENT '요청 CTX_AREA_NK100',
    req_inqr_dvsn_1 TEXT NULL COMMENT '요청 INQR_DVSN_1',
    req_inqr_dvsn_2 TEXT NULL COMMENT '요청 INQR_DVSN_2',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_ord_gno_brno TEXT NULL COMMENT '응답 ord_gno_brno',
    rsp_odno TEXT NULL COMMENT '응답 odno',
    rsp_orgn_odno TEXT NULL COMMENT '응답 orgn_odno',
    rsp_ord_dvsn_name TEXT NULL COMMENT '응답 ord_dvsn_name',
    rsp_pdno TEXT NULL COMMENT '응답 pdno',
    rsp_prdt_name TEXT NULL COMMENT '응답 prdt_name',
    rsp_rvse_cncl_dvsn_name TEXT NULL COMMENT '응답 rvse_cncl_dvsn_name',
    rsp_ord_qty TEXT NULL COMMENT '응답 ord_qty',
    rsp_ord_unpr TEXT NULL COMMENT '응답 ord_unpr',
    rsp_ord_tmd TEXT NULL COMMENT '응답 ord_tmd',
    rsp_tot_ccld_qty TEXT NULL COMMENT '응답 tot_ccld_qty',
    rsp_tot_ccld_amt TEXT NULL COMMENT '응답 tot_ccld_amt',
    rsp_psbl_qty TEXT NULL COMMENT '응답 psbl_qty',
    rsp_sll_buy_dvsn_cd TEXT NULL COMMENT '응답 sll_buy_dvsn_cd',
    rsp_ord_dvsn_cd TEXT NULL COMMENT '응답 ord_dvsn_cd',
    rsp_mgco_aptm_odno TEXT NULL COMMENT '응답 mgco_aptm_odno',
    rsp_excg_dvsn_cd TEXT NULL COMMENT '응답 excg_dvsn_cd',
    rsp_excg_id_dvsn_cd TEXT NULL COMMENT '응답 excg_id_dvsn_cd',
    rsp_excg_id_dvsn_name TEXT NULL COMMENT '응답 excg_id_dvsn_name',
    rsp_stpm_cndt_pric TEXT NULL COMMENT '응답 stpm_cndt_pric',
    rsp_stpm_efct_occr_yn TEXT NULL COMMENT '응답 stpm_efct_occr_yn',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/inquire-psbl-rvsecncl';

-- =============================================================
-- order_resv - 주식예약주문 (CTSC0008U)
-- METHOD: POST
-- URL: /uapi/domestic-stock/v1/trading/order-resv
-- =============================================================
CREATE TABLE IF NOT EXISTS order_resv (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    req_ord_qty TEXT NULL COMMENT '요청 ORD_QTY',
    req_ord_unpr TEXT NULL COMMENT '요청 ORD_UNPR',
    req_sll_buy_dvsn_cd TEXT NULL COMMENT '요청 SLL_BUY_DVSN_CD',
    req_ord_dvsn_cd TEXT NULL COMMENT '요청 ORD_DVSN_CD',
    req_ord_objt_cblc_dvsn_cd TEXT NULL COMMENT '요청 ORD_OBJT_CBLC_DVSN_CD',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_msg TEXT NULL COMMENT '응답 msg',
    rsp_rsvn_ord_seq TEXT NULL COMMENT '응답 rsvn_ord_seq',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/order-resv';

-- =============================================================
-- order_credit - 주식주문(신용) (TTTC0051U)
-- METHOD: POST
-- URL: /uapi/domestic-stock/v1/trading/order-credit
-- =============================================================
CREATE TABLE IF NOT EXISTS order_credit (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_pdno TEXT NULL COMMENT '요청 PDNO',
    req_crdt_type TEXT NULL COMMENT '요청 CRDT_TYPE',
    req_loan_dt TEXT NULL COMMENT '요청 LOAN_DT',
    req_ord_dvsn TEXT NULL COMMENT '요청 ORD_DVSN',
    req_ord_qty TEXT NULL COMMENT '요청 ORD_QTY',
    req_ord_unpr TEXT NULL COMMENT '요청 ORD_UNPR',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_krx_fwdg_ord_orgno TEXT NULL COMMENT '응답 krx_fwdg_ord_orgno',
    rsp_odno TEXT NULL COMMENT '응답 odno',
    rsp_ord_tmd TEXT NULL COMMENT '응답 ord_tmd',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/order-credit';

-- =============================================================
-- pension_inquire_balance - 퇴직연금 잔고조회 (TTTC2208R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/pension/inquire-balance
-- =============================================================
CREATE TABLE IF NOT EXISTS pension_inquire_balance (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_acca_dvsn_cd TEXT NULL COMMENT '요청 ACCA_DVSN_CD',
    req_inqr_dvsn TEXT NULL COMMENT '요청 INQR_DVSN',
    req_ctx_area_fk100 TEXT NULL COMMENT '요청 CTX_AREA_FK100',
    req_ctx_area_nk100 TEXT NULL COMMENT '요청 CTX_AREA_NK100',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_cblc_dvsn_name TEXT NULL COMMENT '응답 cblc_dvsn_name',
    rsp_prdt_name TEXT NULL COMMENT '응답 prdt_name',
    rsp_pdno TEXT NULL COMMENT '응답 pdno',
    rsp_item_dvsn_name TEXT NULL COMMENT '응답 item_dvsn_name',
    rsp_thdt_buyqty TEXT NULL COMMENT '응답 thdt_buyqty',
    rsp_thdt_sll_qty TEXT NULL COMMENT '응답 thdt_sll_qty',
    rsp_hldg_qty TEXT NULL COMMENT '응답 hldg_qty',
    rsp_ord_psbl_qty TEXT NULL COMMENT '응답 ord_psbl_qty',
    rsp_pchs_avg_pric TEXT NULL COMMENT '응답 pchs_avg_pric',
    rsp_pchs_amt TEXT NULL COMMENT '응답 pchs_amt',
    rsp_prpr TEXT NULL COMMENT '응답 prpr',
    rsp_evlu_amt TEXT NULL COMMENT '응답 evlu_amt',
    rsp_evlu_pfls_amt TEXT NULL COMMENT '응답 evlu_pfls_amt',
    rsp_evlu_erng_rt TEXT NULL COMMENT '응답 evlu_erng_rt',
    rsp_dnca_tot_amt TEXT NULL COMMENT '응답 dnca_tot_amt',
    rsp_nxdy_excc_amt TEXT NULL COMMENT '응답 nxdy_excc_amt',
    rsp_prvs_rcdl_excc_amt TEXT NULL COMMENT '응답 prvs_rcdl_excc_amt',
    rsp_thdt_buy_amt TEXT NULL COMMENT '응답 thdt_buy_amt',
    rsp_thdt_sll_amt TEXT NULL COMMENT '응답 thdt_sll_amt',
    rsp_thdt_tlex_amt TEXT NULL COMMENT '응답 thdt_tlex_amt',
    rsp_scts_evlu_amt TEXT NULL COMMENT '응답 scts_evlu_amt',
    rsp_tot_evlu_amt TEXT NULL COMMENT '응답 tot_evlu_amt',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/pension/inquire-balance';

-- =============================================================
-- inquire_balance_rlz_pl - 주식잔고조회_실현손익 (TTTC8494R)
-- METHOD: GET
-- URL: /uapi/domestic-stock/v1/trading/inquire-balance-rlz-pl
-- =============================================================
CREATE TABLE IF NOT EXISTS inquire_balance_rlz_pl (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'PK',
    tr_id VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'TR ID',
    req_url VARCHAR(200) NOT NULL DEFAULT '' COMMENT '요청 URL',
    req_cano TEXT NULL COMMENT '요청 CANO',
    req_acnt_prdt_cd TEXT NULL COMMENT '요청 ACNT_PRDT_CD',
    req_afhr_flpr_yn TEXT NULL COMMENT '요청 AFHR_FLPR_YN',
    req_ofl_yn TEXT NULL COMMENT '요청 OFL_YN',
    req_inqr_dvsn TEXT NULL COMMENT '요청 INQR_DVSN',
    req_unpr_dvsn TEXT NULL COMMENT '요청 UNPR_DVSN',
    req_fund_sttl_icld_yn TEXT NULL COMMENT '요청 FUND_STTL_ICLD_YN',
    req_fncg_amt_auto_rdpt_yn TEXT NULL COMMENT '요청 FNCG_AMT_AUTO_RDPT_YN',
    req_prcs_dvsn TEXT NULL COMMENT '요청 PRCS_DVSN',
    req_cost_icld_yn TEXT NULL COMMENT '요청 COST_ICLD_YN',
    req_ctx_area_fk100 TEXT NULL COMMENT '요청 CTX_AREA_FK100',
    req_ctx_area_nk100 TEXT NULL COMMENT '요청 CTX_AREA_NK100',
    rt_cd VARCHAR(10) NOT NULL DEFAULT '' COMMENT '응답 rt_cd',
    msg_cd VARCHAR(20) NOT NULL DEFAULT '' COMMENT '응답 msg_cd',
    msg1 VARCHAR(255) NOT NULL DEFAULT '' COMMENT '응답 msg1',
    request_json LONGTEXT NULL COMMENT '요청 JSON 원문',
    response_json LONGTEXT NULL COMMENT '응답 JSON 원문',
    rsp_pdno TEXT NULL COMMENT '응답 pdno',
    rsp_prdt_name TEXT NULL COMMENT '응답 prdt_name',
    rsp_trad_dvsn_name TEXT NULL COMMENT '응답 trad_dvsn_name',
    rsp_bfdy_buy_qty TEXT NULL COMMENT '응답 bfdy_buy_qty',
    rsp_bfdy_sll_qty TEXT NULL COMMENT '응답 bfdy_sll_qty',
    rsp_thdt_buyqty TEXT NULL COMMENT '응답 thdt_buyqty',
    rsp_thdt_sll_qty TEXT NULL COMMENT '응답 thdt_sll_qty',
    rsp_hldg_qty TEXT NULL COMMENT '응답 hldg_qty',
    rsp_ord_psbl_qty TEXT NULL COMMENT '응답 ord_psbl_qty',
    rsp_pchs_avg_pric TEXT NULL COMMENT '응답 pchs_avg_pric',
    rsp_pchs_amt TEXT NULL COMMENT '응답 pchs_amt',
    rsp_prpr TEXT NULL COMMENT '응답 prpr',
    rsp_evlu_amt TEXT NULL COMMENT '응답 evlu_amt',
    rsp_evlu_pfls_amt TEXT NULL COMMENT '응답 evlu_pfls_amt',
    rsp_evlu_pfls_rt TEXT NULL COMMENT '응답 evlu_pfls_rt',
    rsp_evlu_erng_rt TEXT NULL COMMENT '응답 evlu_erng_rt',
    rsp_loan_dt TEXT NULL COMMENT '응답 loan_dt',
    rsp_loan_amt TEXT NULL COMMENT '응답 loan_amt',
    rsp_stln_slng_chgs TEXT NULL COMMENT '응답 stln_slng_chgs',
    rsp_expd_dt TEXT NULL COMMENT '응답 expd_dt',
    rsp_stck_loan_unpr TEXT NULL COMMENT '응답 stck_loan_unpr',
    rsp_bfdy_cprs_icdc TEXT NULL COMMENT '응답 bfdy_cprs_icdc',
    rsp_fltt_rt TEXT NULL COMMENT '응답 fltt_rt',
    rsp_dnca_tot_amt TEXT NULL COMMENT '응답 dnca_tot_amt',
    rsp_nxdy_excc_amt TEXT NULL COMMENT '응답 nxdy_excc_amt',
    rsp_prvs_rcdl_excc_amt TEXT NULL COMMENT '응답 prvs_rcdl_excc_amt',
    rsp_cma_evlu_amt TEXT NULL COMMENT '응답 cma_evlu_amt',
    rsp_bfdy_buy_amt TEXT NULL COMMENT '응답 bfdy_buy_amt',
    rsp_thdt_buy_amt TEXT NULL COMMENT '응답 thdt_buy_amt',
    rsp_nxdy_auto_rdpt_amt TEXT NULL COMMENT '응답 nxdy_auto_rdpt_amt',
    rsp_bfdy_sll_amt TEXT NULL COMMENT '응답 bfdy_sll_amt',
    rsp_thdt_sll_amt TEXT NULL COMMENT '응답 thdt_sll_amt',
    rsp_d2_auto_rdpt_amt TEXT NULL COMMENT '응답 d2_auto_rdpt_amt',
    rsp_bfdy_tlex_amt TEXT NULL COMMENT '응답 bfdy_tlex_amt',
    rsp_thdt_tlex_amt TEXT NULL COMMENT '응답 thdt_tlex_amt',
    rsp_tot_loan_amt TEXT NULL COMMENT '응답 tot_loan_amt',
    rsp_scts_evlu_amt TEXT NULL COMMENT '응답 scts_evlu_amt',
    rsp_tot_evlu_amt TEXT NULL COMMENT '응답 tot_evlu_amt',
    rsp_nass_amt TEXT NULL COMMENT '응답 nass_amt',
    rsp_fncg_gld_auto_rdpt_yn TEXT NULL COMMENT '응답 fncg_gld_auto_rdpt_yn',
    rsp_pchs_amt_smtl_amt TEXT NULL COMMENT '응답 pchs_amt_smtl_amt',
    rsp_evlu_amt_smtl_amt TEXT NULL COMMENT '응답 evlu_amt_smtl_amt',
    rsp_evlu_pfls_smtl_amt TEXT NULL COMMENT '응답 evlu_pfls_smtl_amt',
    rsp_tot_stln_slng_chgs TEXT NULL COMMENT '응답 tot_stln_slng_chgs',
    rsp_bfdy_tot_asst_evlu_amt TEXT NULL COMMENT '응답 bfdy_tot_asst_evlu_amt',
    rsp_asst_icdc_amt TEXT NULL COMMENT '응답 asst_icdc_amt',
    rsp_asst_icdc_erng_rt TEXT NULL COMMENT '응답 asst_icdc_erng_rt',
    rsp_rlzt_pfls TEXT NULL COMMENT '응답 rlzt_pfls',
    rsp_rlzt_erng_rt TEXT NULL COMMENT '응답 rlzt_erng_rt',
    rsp_real_evlu_pfls TEXT NULL COMMENT '응답 real_evlu_pfls',
    rsp_real_evlu_pfls_erng_rt TEXT NULL COMMENT '응답 real_evlu_pfls_erng_rt',
    fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집일시',
    PRIMARY KEY (id),
    INDEX idx_req_dt (fetched_at),
    INDEX idx_tr_id (tr_id),
    INDEX idx_rt_cd (rt_cd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='trading/inquire-balance-rlz-pl';
