# WebSocket API 요청 스펙 정의
# 각 항목: api_id, name, overview, fields, request_example

WEBSOCKET_API_SPECS = [
    {
        'api_id': '00',
        'name': '주문체결',
        'overview': '실시간 항목 00(주문체결)은 종목코드(item) 등록과 상관 없이 ACCESS TOKEN을 발급한 계좌에 주문 접수, 체결, 정정, 취소 등 매매가 발생할 경우 데이터가 수신됩니다.   ACCESS TOKEN 발급과 상관없이 해당 종목의 체결내역을 보고싶으신 경우에 0B를 이용 부탁드립니다.',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': ''},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": [""], "type": ["00"]}]},
    },
    {
        'api_id': '04',
        'name': '잔고',
        'overview': '실시간 항목 04(잔고)는 종목코드(item) 등록과 상관 없이 ACCESS TOKEN을 발급한 계좌에 주문 체결이 발생할 경우 데이터가 수신됩니다.',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': ''},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": [""], "type": ["04"]}]},
    },
    {
        'api_id': '0A',
        'name': '주식기세',
        'overview': '특정 종목이 기세일때 발생하는 데이터로 시장에서 체결없이 현재가가 변경되는 대량매매나 거래소에서 종목 종가데이터 보정시 발생하는 실시간 입니다.',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["005930"], "type": ["0A"]}]},
    },
    {
        'api_id': '0B',
        'name': '주식체결',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["005930"], "type": ["0B"]}]},
    },
    {
        'api_id': '0C',
        'name': '주식우선호가',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["005930"], "type": ["0C"]}]},
    },
    {
        'api_id': '0D',
        'name': '주식호가잔량',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["005930"], "type": ["0D"]}]},
    },
    {
        'api_id': '0E',
        'name': '주식시간외호가',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["005930"], "type": ["0E"]}]},
    },
    {
        'api_id': '0F',
        'name': '주식당일거래원',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["005930"], "type": ["0F"]}]},
    },
    {
        'api_id': '0G',
        'name': 'ETF NAV',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["069500"], "type": ["0G"]}]},
    },
    {
        'api_id': '0H',
        'name': '주식예상체결',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["005930"], "type": ["0H"]}]},
    },
    {
        'api_id': '0I',
        'name': '국제금환산가격',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': 'MGD: 원/g, MGU: $/온스,소수점2자리'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["MGD"], "type": ["0I"]}]},
    },
    {
        'api_id': '0J',
        'name': '업종지수',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["001"], "type": ["0J"]}]},
    },
    {
        'api_id': '0U',
        'name': '업종등락',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["001"], "type": ["0U"]}]},
    },
    {
        'api_id': '0g',
        'name': '주식종목정보',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["005930"], "type": ["0g"]}]},
    },
    {
        'api_id': '0m',
        'name': 'ELW 이론가',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["57JBHH"], "type": ["0m"]}]},
    },
    {
        'api_id': '0s',
        'name': '장시작시간',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": [""], "type": ["0s"]}]},
    },
    {
        'api_id': '0u',
        'name': 'ELW 지표',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["57JBHH"], "type": ["0u"]}]},
    },
    {
        'api_id': '0w',
        'name': '종목프로그램매매',
        'overview': '',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': '- item', 'label': '실시간 등록 요소', 'required': False, 'description': '거래소별 종목코드, 업종코드 (KRX:039490,NXT:039490_NX,SOR:039490_AL)'},
            {'element': '- type', 'label': '실시간 항목', 'required': True, 'description': 'TR 명(0A,0B....)'},
        ],
        'request_example': {"trnm": "REG", "grp_no": "1", "refresh": "1", "data": [{"item": ["005930"], "type": ["0w"]}]},
    },
    {
        'api_id': 'ka10171',
        'name': '조건검색 목록조회',
        'overview': '조건검색은 영웅문4에서 만드실 수 있습니다.',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
        ],
        'request_example': {"trnm": "CNSRLST"},
    },
    {
        'api_id': 'ka10172',
        'name': '조건검색 요청 일반',
        'overview': '조건검색은 영웅문4에서 만드실 수 있습니다.',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': 'seq', 'label': '조건검색식 일련번호', 'required': True, 'description': ''},
            {'element': 'search_type', 'label': '조회타입', 'required': True, 'description': '0:조건검색'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': 'K:KRX'},
        ],
        'request_example': {"trnm": "CNSRREQ", "seq": "4", "search_type": "0", "stex_tp": "K", "cont_yn": "N", "next_key": ""},
    },
    {
        'api_id': 'ka10173',
        'name': '조건검색 요청 실시간',
        'overview': '조건검색 실시간 조회는 시스템 내부구조상 조건검색 목록 조회를 먼저 진행한 후에 실시간 조회를 이용할 수 있습니다.  조건검색은 영웅문4에서 만드실 수 있습니다.',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': 'seq', 'label': '조건검색식 일련번호', 'required': True, 'description': ''},
            {'element': 'search_type', 'label': '조회타입', 'required': True, 'description': '1: 조건검색+실시간조건검색'},
            {'element': 'stex_tp', 'label': '거래소구분', 'required': True, 'description': 'K:KRX'},
        ],
        'request_example': {"trnm": "CNSRREQ", "seq": "4", "search_type": "1", "stex_tp": "K"},
    },
    {
        'api_id': 'ka10174',
        'name': '조건검색 실시간 해제',
        'overview': '조건검색은 영웅문4에서 만드실 수 있습니다.',
        'fields': [
            {'element': 'trnm', 'label': '서비스명', 'required': True, 'description': 'REG:등록, REMOVE:해지'},
            {'element': 'grp_no', 'label': '그룹번호', 'required': True, 'description': ''},
            {'element': 'refresh', 'label': '기존등록유지여부', 'required': True, 'description': '1:유지, 0:해제'},
            {'element': 'data', 'label': '실시간 등록 리스트', 'required': True, 'description': ''},
            {'element': 'seq', 'label': '조건검색식 일련번호', 'required': True, 'description': ''},
        ],
        'request_example': {"trnm": "CNSRCLR", "seq": "1"},
    },
]
