"""정적 계좌 API 응답 스펙 정의."""

ACCOUNT_RESPONSE_SPECS = {
    'ka00001': [
        {'element': 'acctNo', 'label': '계좌번호', 'type': 'String', 'description': ''},
    ],
    'ka01690': [
        {'element': 'dt', 'label': '일자', 'type': 'String', 'description': ''},
        {'element': 'tot_buy_amt', 'label': '총 매입가', 'type': 'String', 'description': ''},
        {'element': 'tot_evlt_amt', 'label': '총 평가금액', 'type': 'String', 'description': ''},
        {'element': 'tot_evltv_prft', 'label': '총 평가손익', 'type': 'String', 'description': ''},
        {'element': 'tot_prft_rt', 'label': '수익률', 'type': 'String', 'description': ''},
        {'element': 'dbst_bal', 'label': '예수금', 'type': 'String', 'description': ''},
        {'element': 'day_stk_asst', 'label': '추정자산', 'type': 'String', 'description': ''},
        {'element': 'buy_wght', 'label': '현금비중', 'type': 'String', 'description': ''},
        {'element': 'day_bal_rt', 'label': '일별잔고수익률', 'type': 'LIST', 'description': ''},
        {'element': '- cur_prc', 'label': '현재가', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- rmnd_qty', 'label': '보유 수량', 'type': 'String', 'description': ''},
        {'element': '- buy_uv', 'label': '매입 단가', 'type': 'String', 'description': ''},
        {'element': '- buy_wght', 'label': '매수비중', 'type': 'String', 'description': ''},
        {'element': '- evltv_prft', 'label': '평가손익', 'type': 'String', 'description': ''},
        {'element': '- prft_rt', 'label': '수익률', 'type': 'String', 'description': ''},
        {'element': '- evlt_amt', 'label': '평가금액', 'type': 'String', 'description': ''},
        {'element': '- evlt_wght', 'label': '평가비중', 'type': 'String', 'description': ''},
    ],
    'ka10072': [
        {'element': 'dt_stk_div_rlzt_pl', 'label': '일자별종목별실현손익', 'type': 'LIST', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- cntr_qty', 'label': '체결량', 'type': 'String', 'description': ''},
        {'element': '- buy_uv', 'label': '매입단가', 'type': 'String', 'description': ''},
        {'element': '- cntr_pric', 'label': '체결가', 'type': 'String', 'description': ''},
        {'element': '- tdy_sel_pl', 'label': '당일매도손익', 'type': 'String', 'description': ''},
        {'element': '- pl_rt', 'label': '손익율', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_cmsn', 'label': '당일매매수수료', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_tax', 'label': '당일매매세금', 'type': 'String', 'description': ''},
        {'element': '- wthd_alowa', 'label': '인출가능금액', 'type': 'String', 'description': ''},
        {'element': '- loan_dt', 'label': '대출일', 'type': 'String', 'description': ''},
        {'element': '- crd_tp', 'label': '신용구분', 'type': 'String', 'description': ''},
        {'element': '- stk_cd_1', 'label': '종목코드1', 'type': 'String', 'description': ''},
        {'element': '- tdy_sel_pl_1', 'label': '당일매도손익1', 'type': 'String', 'description': ''},
    ],
    'ka10073': [
        {'element': 'dt_stk_rlzt_pl', 'label': '일자별종목별실현손익', 'type': 'LIST', 'description': ''},
        {'element': '- dt', 'label': '일자', 'type': 'String', 'description': ''},
        {'element': '- tdy_htssel_cmsn', 'label': '당일hts매도수수료', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- cntr_qty', 'label': '체결량', 'type': 'String', 'description': ''},
        {'element': '- buy_uv', 'label': '매입단가', 'type': 'String', 'description': ''},
        {'element': '- cntr_pric', 'label': '체결가', 'type': 'String', 'description': ''},
        {'element': '- tdy_sel_pl', 'label': '당일매도손익', 'type': 'String', 'description': ''},
        {'element': '- pl_rt', 'label': '손익율', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_cmsn', 'label': '당일매매수수료', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_tax', 'label': '당일매매세금', 'type': 'String', 'description': ''},
        {'element': '- wthd_alowa', 'label': '인출가능금액', 'type': 'String', 'description': ''},
        {'element': '- loan_dt', 'label': '대출일', 'type': 'String', 'description': ''},
        {'element': '- crd_tp', 'label': '신용구분', 'type': 'String', 'description': ''},
    ],
    'ka10074': [
        {'element': 'tot_buy_amt', 'label': '총매수금액', 'type': 'String', 'description': ''},
        {'element': 'tot_sell_amt', 'label': '총매도금액', 'type': 'String', 'description': ''},
        {'element': 'rlzt_pl', 'label': '실현손익', 'type': 'String', 'description': ''},
        {'element': 'trde_cmsn', 'label': '매매수수료', 'type': 'String', 'description': ''},
        {'element': 'trde_tax', 'label': '매매세금', 'type': 'String', 'description': ''},
        {'element': 'dt_rlzt_pl', 'label': '일자별실현손익', 'type': 'LIST', 'description': ''},
        {'element': '- dt', 'label': '일자', 'type': 'String', 'description': ''},
        {'element': '- buy_amt', 'label': '매수금액', 'type': 'String', 'description': ''},
        {'element': '- sell_amt', 'label': '매도금액', 'type': 'String', 'description': ''},
        {'element': '- tdy_sel_pl', 'label': '당일매도손익', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_cmsn', 'label': '당일매매수수료', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_tax', 'label': '당일매매세금', 'type': 'String', 'description': ''},
    ],
    'ka10075': [
        {'element': 'oso', 'label': '미체결', 'type': 'LIST', 'description': ''},
        {'element': '- acnt_no', 'label': '계좌번호', 'type': 'String', 'description': ''},
        {'element': '- ord_no', 'label': '주문번호', 'type': 'String', 'description': ''},
        {'element': '- mang_empno', 'label': '관리사번', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
        {'element': '- tsk_tp', 'label': '업무구분', 'type': 'String', 'description': ''},
        {'element': '- ord_stt', 'label': '주문상태', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- ord_qty', 'label': '주문수량', 'type': 'String', 'description': ''},
        {'element': '- ord_pric', 'label': '주문가격', 'type': 'String', 'description': ''},
        {'element': '- oso_qty', 'label': '미체결수량', 'type': 'String', 'description': ''},
        {'element': '- cntr_tot_amt', 'label': '체결누계금액', 'type': 'String', 'description': ''},
        {'element': '- orig_ord_no', 'label': '원주문번호', 'type': 'String', 'description': ''},
        {'element': '- io_tp_nm', 'label': '주문구분', 'type': 'String', 'description': ''},
        {'element': '- trde_tp', 'label': '매매구분', 'type': 'String', 'description': ''},
        {'element': '- tm', 'label': '시간', 'type': 'String', 'description': ''},
        {'element': '- cntr_no', 'label': '체결번호', 'type': 'String', 'description': ''},
        {'element': '- cntr_pric', 'label': '체결가', 'type': 'String', 'description': ''},
        {'element': '- cntr_qty', 'label': '체결량', 'type': 'String', 'description': ''},
        {'element': '- cur_prc', 'label': '현재가', 'type': 'String', 'description': ''},
        {'element': '- sel_bid', 'label': '매도호가', 'type': 'String', 'description': ''},
        {'element': '- buy_bid', 'label': '매수호가', 'type': 'String', 'description': ''},
        {'element': '- unit_cntr_pric', 'label': '단위체결가', 'type': 'String', 'description': ''},
        {'element': '- unit_cntr_qty', 'label': '단위체결량', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_cmsn', 'label': '당일매매수수료', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_tax', 'label': '당일매매세금', 'type': 'String', 'description': ''},
        {'element': '- ind_invsr', 'label': '개인투자자', 'type': 'String', 'description': ''},
        {'element': '- stex_tp', 'label': '거래소구분', 'type': 'String', 'description': '0 : 통합, 1 : KRX, 2 : NXT'},
        {'element': '- stex_tp_txt', 'label': '거래소구분텍스트', 'type': 'String', 'description': '통합,KRX,NXT'},
        {'element': '- sor_yn', 'label': 'SOR 여부값', 'type': 'String', 'description': 'Y,N'},
        {'element': '- stop_pric', 'label': '스톱가', 'type': 'String', 'description': '스톱지정가주문 스톱가'},
    ],
    'ka10076': [
        {'element': 'cntr', 'label': '체결', 'type': 'LIST', 'description': ''},
        {'element': '- ord_no', 'label': '주문번호', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- io_tp_nm', 'label': '주문구분', 'type': 'String', 'description': ''},
        {'element': '- ord_pric', 'label': '주문가격', 'type': 'String', 'description': ''},
        {'element': '- ord_qty', 'label': '주문수량', 'type': 'String', 'description': ''},
        {'element': '- cntr_pric', 'label': '체결가', 'type': 'String', 'description': ''},
        {'element': '- cntr_qty', 'label': '체결량', 'type': 'String', 'description': ''},
        {'element': '- oso_qty', 'label': '미체결수량', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_cmsn', 'label': '당일매매수수료', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_tax', 'label': '당일매매세금', 'type': 'String', 'description': ''},
        {'element': '- ord_stt', 'label': '주문상태', 'type': 'String', 'description': ''},
        {'element': '- trde_tp', 'label': '매매구분', 'type': 'String', 'description': ''},
        {'element': '- orig_ord_no', 'label': '원주문번호', 'type': 'String', 'description': ''},
        {'element': '- ord_tm', 'label': '주문시간', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
        {'element': '- stex_tp', 'label': '거래소구분', 'type': 'String', 'description': '0 : 통합, 1 : KRX, 2 : NXT'},
        {'element': '- stex_tp_txt', 'label': '거래소구분텍스트', 'type': 'String', 'description': '통합,KRX,NXT'},
        {'element': '- sor_yn', 'label': 'SOR 여부값', 'type': 'String', 'description': 'Y,N'},
        {'element': '- stop_pric', 'label': '스톱가', 'type': 'String', 'description': '스톱지정가주문 스톱가'},
    ],
    'ka10077': [
        {'element': 'tdy_rlzt_pl', 'label': '당일실현손익', 'type': 'String', 'description': ''},
        {'element': 'tdy_rlzt_pl_dtl', 'label': '당일실현손익상세', 'type': 'LIST', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- cntr_qty', 'label': '체결량', 'type': 'String', 'description': ''},
        {'element': '- buy_uv', 'label': '매입단가', 'type': 'String', 'description': ''},
        {'element': '- cntr_pric', 'label': '체결가', 'type': 'String', 'description': ''},
        {'element': '- tdy_sel_pl', 'label': '당일매도손익', 'type': 'String', 'description': ''},
        {'element': '- pl_rt', 'label': '손익율', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_cmsn', 'label': '당일매매수수료', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_tax', 'label': '당일매매세금', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
    ],
    'ka10085': [
        {'element': 'acnt_prft_rt', 'label': '계좌수익률', 'type': 'LIST', 'description': ''},
        {'element': '- dt', 'label': '일자', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- cur_prc', 'label': '현재가', 'type': 'String', 'description': ''},
        {'element': '- pur_pric', 'label': '매입가', 'type': 'String', 'description': ''},
        {'element': '- pur_amt', 'label': '매입금액', 'type': 'String', 'description': ''},
        {'element': '- rmnd_qty', 'label': '보유수량', 'type': 'String', 'description': ''},
        {'element': '- tdy_sel_pl', 'label': '당일매도손익', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_cmsn', 'label': '당일매매수수료', 'type': 'String', 'description': ''},
        {'element': '- tdy_trde_tax', 'label': '당일매매세금', 'type': 'String', 'description': ''},
        {'element': '- crd_tp', 'label': '신용구분', 'type': 'String', 'description': ''},
        {'element': '- loan_dt', 'label': '대출일', 'type': 'String', 'description': ''},
        {'element': '- setl_remn', 'label': '결제잔고', 'type': 'String', 'description': ''},
        {'element': '- clrn_alow_qty', 'label': '청산가능수량', 'type': 'String', 'description': ''},
        {'element': '- crd_amt', 'label': '신용금액', 'type': 'String', 'description': ''},
        {'element': '- crd_int', 'label': '신용이자', 'type': 'String', 'description': ''},
        {'element': '- expr_dt', 'label': '만기일', 'type': 'String', 'description': ''},
    ],
    'ka10088': [
        {'element': 'osop', 'label': '미체결분할주문리스트', 'type': 'LIST', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- ord_no', 'label': '주문번호', 'type': 'String', 'description': ''},
        {'element': '- ord_qty', 'label': '주문수량', 'type': 'String', 'description': ''},
        {'element': '- ord_pric', 'label': '주문가격', 'type': 'String', 'description': ''},
        {'element': '- osop_qty', 'label': '미체결수량', 'type': 'String', 'description': ''},
        {'element': '- io_tp_nm', 'label': '주문구분', 'type': 'String', 'description': ''},
        {'element': '- trde_tp', 'label': '매매구분', 'type': 'String', 'description': ''},
        {'element': '- sell_tp', 'label': '매도/수 구분', 'type': 'String', 'description': ''},
        {'element': '- cntr_qty', 'label': '체결량', 'type': 'String', 'description': ''},
        {'element': '- ord_stt', 'label': '주문상태', 'type': 'String', 'description': ''},
        {'element': '- cur_prc', 'label': '현재가', 'type': 'String', 'description': ''},
        {'element': '- stex_tp', 'label': '거래소구분', 'type': 'String', 'description': '0 : 통합, 1 : KRX, 2 : NXT'},
        {'element': '- stex_tp_txt', 'label': '거래소구분텍스트', 'type': 'String', 'description': '통합,KRX,NXT'},
    ],
    'ka10170': [
        {'element': 'tot_sell_amt', 'label': '총매도금액', 'type': 'String', 'description': ''},
        {'element': 'tot_buy_amt', 'label': '총매수금액', 'type': 'String', 'description': ''},
        {'element': 'tot_cmsn_tax', 'label': '총수수료_세금', 'type': 'String', 'description': ''},
        {'element': 'tot_exct_amt', 'label': '총정산금액', 'type': 'String', 'description': ''},
        {'element': 'tot_pl_amt', 'label': '총손익금액', 'type': 'String', 'description': ''},
        {'element': 'tot_prft_rt', 'label': '총수익률', 'type': 'String', 'description': ''},
        {'element': 'tdy_trde_diary', 'label': '당일매매일지', 'type': 'LIST', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- buy_avg_pric', 'label': '매수평균가', 'type': 'String', 'description': ''},
        {'element': '- buy_qty', 'label': '매수수량', 'type': 'String', 'description': ''},
        {'element': '- sel_avg_pric', 'label': '매도평균가', 'type': 'String', 'description': ''},
        {'element': '- sell_qty', 'label': '매도수량', 'type': 'String', 'description': ''},
        {'element': '- cmsn_alm_tax', 'label': '수수료_제세금', 'type': 'String', 'description': ''},
        {'element': '- pl_amt', 'label': '손익금액', 'type': 'String', 'description': ''},
        {'element': '- sell_amt', 'label': '매도금액', 'type': 'String', 'description': ''},
        {'element': '- buy_amt', 'label': '매수금액', 'type': 'String', 'description': ''},
        {'element': '- prft_rt', 'label': '수익률', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
    ],
    'kt00001': [
        {'element': 'entr', 'label': '예수금', 'type': 'String', 'description': ''},
        {'element': 'profa_ch', 'label': '주식증거금현금', 'type': 'String', 'description': ''},
        {'element': 'bncr_profa_ch', 'label': '수익증권증거금현금', 'type': 'String', 'description': ''},
        {'element': 'nxdy_bncr_sell_exct', 'label': '익일수익증권매도정산대금', 'type': 'String', 'description': ''},
        {'element': 'fc_stk_krw_repl_set_amt', 'label': '해외주식원화대용설정금', 'type': 'String', 'description': ''},
        {'element': 'crd_grnta_ch', 'label': '신용보증금현금', 'type': 'String', 'description': ''},
        {'element': 'crd_grnt_ch', 'label': '신용담보금현금', 'type': 'String', 'description': ''},
        {'element': 'add_grnt_ch', 'label': '추가담보금현금', 'type': 'String', 'description': ''},
        {'element': 'etc_profa', 'label': '기타증거금', 'type': 'String', 'description': ''},
        {'element': 'uncl_stk_amt', 'label': '미수확보금', 'type': 'String', 'description': ''},
        {'element': 'shrts_prica', 'label': '공매도대금', 'type': 'String', 'description': ''},
        {'element': 'crd_set_grnta', 'label': '신용설정평가금', 'type': 'String', 'description': ''},
        {'element': 'chck_ina_amt', 'label': '수표입금액', 'type': 'String', 'description': ''},
        {'element': 'etc_chck_ina_amt', 'label': '기타수표입금액', 'type': 'String', 'description': ''},
        {'element': 'crd_grnt_ruse', 'label': '신용담보재사용', 'type': 'String', 'description': ''},
        {'element': 'knx_asset_evltv', 'label': '코넥스기본예탁금', 'type': 'String', 'description': ''},
        {'element': 'elwdpst_evlta', 'label': 'ELW예탁평가금', 'type': 'String', 'description': ''},
        {'element': 'crd_ls_rght_frcs_amt', 'label': '신용대주권리예정금액', 'type': 'String', 'description': ''},
        {'element': 'lvlh_join_amt', 'label': '생계형가입금액', 'type': 'String', 'description': ''},
        {'element': 'lvlh_trns_alowa', 'label': '생계형입금가능금액', 'type': 'String', 'description': ''},
        {'element': 'repl_amt', 'label': '대용금평가금액(합계)', 'type': 'String', 'description': ''},
        {'element': 'remn_repl_evlta', 'label': '잔고대용평가금액', 'type': 'String', 'description': ''},
        {'element': 'trst_remn_repl_evlta', 'label': '위탁대용잔고평가금액', 'type': 'String', 'description': ''},
        {'element': 'bncr_remn_repl_evlta', 'label': '수익증권대용평가금액', 'type': 'String', 'description': ''},
        {'element': 'profa_repl', 'label': '위탁증거금대용', 'type': 'String', 'description': ''},
        {'element': 'crd_grnta_repl', 'label': '신용보증금대용', 'type': 'String', 'description': ''},
        {'element': 'crd_grnt_repl', 'label': '신용담보금대용', 'type': 'String', 'description': ''},
        {'element': 'add_grnt_repl', 'label': '추가담보금대용', 'type': 'String', 'description': ''},
        {'element': 'rght_repl_amt', 'label': '권리대용금', 'type': 'String', 'description': ''},
        {'element': 'pymn_alow_amt', 'label': '출금가능금액', 'type': 'String', 'description': ''},
        {'element': 'wrap_pymn_alow_amt', 'label': '랩출금가능금액', 'type': 'String', 'description': ''},
        {'element': 'ord_alow_amt', 'label': '주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'bncr_buy_alowa', 'label': '수익증권매수가능금액', 'type': 'String', 'description': ''},
        {'element': '20stk_ord_alow_amt', 'label': '20%종목주문가능금액', 'type': 'String', 'description': ''},
        {'element': '30stk_ord_alow_amt', 'label': '30%종목주문가능금액', 'type': 'String', 'description': ''},
        {'element': '40stk_ord_alow_amt', 'label': '40%종목주문가능금액', 'type': 'String', 'description': ''},
        {'element': '100stk_ord_alow_amt', 'label': '100%종목주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'ch_uncla', 'label': '현금미수금', 'type': 'String', 'description': ''},
        {'element': 'ch_uncla_dlfe', 'label': '현금미수연체료', 'type': 'String', 'description': ''},
        {'element': 'ch_uncla_tot', 'label': '현금미수금합계', 'type': 'String', 'description': ''},
        {'element': 'crd_int_npay', 'label': '신용이자미납', 'type': 'String', 'description': ''},
        {'element': 'int_npay_amt_dlfe', 'label': '신용이자미납연체료', 'type': 'String', 'description': ''},
        {'element': 'int_npay_amt_tot', 'label': '신용이자미납합계', 'type': 'String', 'description': ''},
        {'element': 'etc_loana', 'label': '기타대여금', 'type': 'String', 'description': ''},
        {'element': 'etc_loana_dlfe', 'label': '기타대여금연체료', 'type': 'String', 'description': ''},
        {'element': 'etc_loan_tot', 'label': '기타대여금합계', 'type': 'String', 'description': ''},
        {'element': 'nrpy_loan', 'label': '미상환융자금', 'type': 'String', 'description': ''},
        {'element': 'loan_sum', 'label': '융자금합계', 'type': 'String', 'description': ''},
        {'element': 'ls_sum', 'label': '대주금합계', 'type': 'String', 'description': ''},
        {'element': 'crd_grnt_rt', 'label': '신용담보비율', 'type': 'String', 'description': ''},
        {'element': 'mdstrm_usfe', 'label': '중도이용료', 'type': 'String', 'description': ''},
        {'element': 'min_ord_alow_yn', 'label': '최소주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'loan_remn_evlt_amt', 'label': '대출총평가금액', 'type': 'String', 'description': ''},
        {'element': 'dpst_grntl_remn', 'label': '예탁담보대출잔고', 'type': 'String', 'description': ''},
        {'element': 'sell_grntl_remn', 'label': '매도담보대출잔고', 'type': 'String', 'description': ''},
        {'element': 'd1_entra', 'label': 'd+1추정예수금', 'type': 'String', 'description': ''},
        {'element': 'd1_slby_exct_amt', 'label': 'd+1매도매수정산금', 'type': 'String', 'description': ''},
        {'element': 'd1_buy_exct_amt', 'label': 'd+1매수정산금', 'type': 'String', 'description': ''},
        {'element': 'd1_out_rep_mor', 'label': 'd+1미수변제소요금', 'type': 'String', 'description': ''},
        {'element': 'd1_sel_exct_amt', 'label': 'd+1매도정산금', 'type': 'String', 'description': ''},
        {'element': 'd1_pymn_alow_amt', 'label': 'd+1출금가능금액', 'type': 'String', 'description': ''},
        {'element': 'd2_entra', 'label': 'd+2추정예수금', 'type': 'String', 'description': ''},
        {'element': 'd2_slby_exct_amt', 'label': 'd+2매도매수정산금', 'type': 'String', 'description': ''},
        {'element': 'd2_buy_exct_amt', 'label': 'd+2매수정산금', 'type': 'String', 'description': ''},
        {'element': 'd2_out_rep_mor', 'label': 'd+2미수변제소요금', 'type': 'String', 'description': ''},
        {'element': 'd2_sel_exct_amt', 'label': 'd+2매도정산금', 'type': 'String', 'description': ''},
        {'element': 'd2_pymn_alow_amt', 'label': 'd+2출금가능금액', 'type': 'String', 'description': ''},
        {'element': '50stk_ord_alow_amt', 'label': '50%종목주문가능금액', 'type': 'String', 'description': ''},
        {'element': '60stk_ord_alow_amt', 'label': '60%종목주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'stk_entr_prst', 'label': '종목별예수금', 'type': 'LIST', 'description': ''},
        {'element': '- crnc_cd', 'label': '통화코드', 'type': 'String', 'description': ''},
        {'element': '- fx_entr', 'label': '외화예수금', 'type': 'String', 'description': ''},
        {'element': '- fc_krw_repl_evlta', 'label': '원화대용평가금', 'type': 'String', 'description': ''},
        {'element': '- fc_trst_profa', 'label': '해외주식증거금', 'type': 'String', 'description': ''},
        {'element': '- pymn_alow_amt_entr', 'label': '출금가능금액(예수금)', 'type': 'String', 'description': ''},
        {'element': '- pymn_alow_amt', 'label': '출금가능금액', 'type': 'String', 'description': ''},
        {'element': '- ord_alow_amt_entr', 'label': '주문가능금액(예수금)', 'type': 'String', 'description': ''},
        {'element': '- fc_uncla', 'label': '외화미수(합계)', 'type': 'String', 'description': ''},
        {'element': '- fc_ch_uncla', 'label': '외화현금미수금', 'type': 'String', 'description': ''},
        {'element': '- dly_amt', 'label': '연체료', 'type': 'String', 'description': ''},
        {'element': '- d1_fx_entr', 'label': 'd+1외화예수금', 'type': 'String', 'description': ''},
        {'element': '- d2_fx_entr', 'label': 'd+2외화예수금', 'type': 'String', 'description': ''},
        {'element': '- d3_fx_entr', 'label': 'd+3외화예수금', 'type': 'String', 'description': ''},
        {'element': '- d4_fx_entr', 'label': 'd+4외화예수금', 'type': 'String', 'description': ''},
    ],
    'kt00002': [
        {'element': 'daly_prsm_dpst_aset_amt_prst', 'label': '일별추정예탁자산현황', 'type': 'LIST', 'description': ''},
        {'element': '- dt', 'label': '일자', 'type': 'String', 'description': ''},
        {'element': '- entr', 'label': '예수금', 'type': 'String', 'description': ''},
        {'element': '- grnt_use_amt', 'label': '담보대출금', 'type': 'String', 'description': ''},
        {'element': '- crd_loan', 'label': '신용융자금', 'type': 'String', 'description': ''},
        {'element': '- ls_grnt', 'label': '대주담보금', 'type': 'String', 'description': ''},
        {'element': '- repl_amt', 'label': '대용금', 'type': 'String', 'description': ''},
        {'element': '- prsm_dpst_aset_amt', 'label': '추정예탁자산', 'type': 'String', 'description': ''},
        {'element': '- prsm_dpst_aset_amt_bncr_skip', 'label': '추정예탁자산수익증권제외', 'type': 'String', 'description': ''},
    ],
    'kt00003': [
        {'element': 'prsm_dpst_aset_amt', 'label': '추정예탁자산', 'type': 'String', 'description': ''},
    ],
    'kt00004': [
        {'element': 'acnt_nm', 'label': '계좌명', 'type': 'String', 'description': ''},
        {'element': 'brch_nm', 'label': '지점명', 'type': 'String', 'description': ''},
        {'element': 'entr', 'label': '예수금', 'type': 'String', 'description': ''},
        {'element': 'd2_entra', 'label': 'D+2추정예수금', 'type': 'String', 'description': ''},
        {'element': 'tot_est_amt', 'label': '유가잔고평가액', 'type': 'String', 'description': ''},
        {'element': 'aset_evlt_amt', 'label': '예탁자산평가액', 'type': 'String', 'description': ''},
        {'element': 'tot_pur_amt', 'label': '총매입금액', 'type': 'String', 'description': ''},
        {'element': 'prsm_dpst_aset_amt', 'label': '추정예탁자산', 'type': 'String', 'description': ''},
        {'element': 'tot_grnt_sella', 'label': '매도담보대출금', 'type': 'String', 'description': ''},
        {'element': 'tdy_lspft_amt', 'label': '당일투자원금', 'type': 'String', 'description': ''},
        {'element': 'invt_bsamt', 'label': '당월투자원금', 'type': 'String', 'description': ''},
        {'element': 'lspft_amt', 'label': '누적투자원금', 'type': 'String', 'description': ''},
        {'element': 'tdy_lspft', 'label': '당일투자손익', 'type': 'String', 'description': ''},
        {'element': 'lspft2', 'label': '당월투자손익', 'type': 'String', 'description': ''},
        {'element': 'lspft', 'label': '누적투자손익', 'type': 'String', 'description': ''},
        {'element': 'tdy_lspft_rt', 'label': '당일손익율', 'type': 'String', 'description': ''},
        {'element': 'lspft_ratio', 'label': '당월손익율', 'type': 'String', 'description': ''},
        {'element': 'lspft_rt', 'label': '누적손익율', 'type': 'String', 'description': ''},
        {'element': 'stk_acnt_evlt_prst', 'label': '종목별계좌평가현황', 'type': 'LIST', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- rmnd_qty', 'label': '보유수량', 'type': 'String', 'description': ''},
        {'element': '- avg_prc', 'label': '평균단가', 'type': 'String', 'description': ''},
        {'element': '- cur_prc', 'label': '현재가', 'type': 'String', 'description': ''},
        {'element': '- evlt_amt', 'label': '평가금액', 'type': 'String', 'description': ''},
        {'element': '- pl_amt', 'label': '손익금액', 'type': 'String', 'description': ''},
        {'element': '- pl_rt', 'label': '손익율', 'type': 'String', 'description': ''},
        {'element': '- loan_dt', 'label': '대출일', 'type': 'String', 'description': ''},
        {'element': '- pur_amt', 'label': '매입금액', 'type': 'String', 'description': ''},
        {'element': '- setl_remn', 'label': '결제잔고', 'type': 'String', 'description': ''},
        {'element': '- pred_buyq', 'label': '전일매수수량', 'type': 'String', 'description': ''},
        {'element': '- pred_sellq', 'label': '전일매도수량', 'type': 'String', 'description': ''},
        {'element': '- tdy_buyq', 'label': '금일매수수량', 'type': 'String', 'description': ''},
        {'element': '- tdy_sellq', 'label': '금일매도수량', 'type': 'String', 'description': ''},
    ],
    'kt00005': [
        {'element': 'entr', 'label': '예수금', 'type': 'String', 'description': ''},
        {'element': 'entr_d1', 'label': '예수금D+1', 'type': 'String', 'description': ''},
        {'element': 'entr_d2', 'label': '예수금D+2', 'type': 'String', 'description': ''},
        {'element': 'pymn_alow_amt', 'label': '출금가능금액', 'type': 'String', 'description': ''},
        {'element': 'uncl_stk_amt', 'label': '미수확보금', 'type': 'String', 'description': ''},
        {'element': 'repl_amt', 'label': '대용금', 'type': 'String', 'description': ''},
        {'element': 'rght_repl_amt', 'label': '권리대용금', 'type': 'String', 'description': ''},
        {'element': 'ord_alowa', 'label': '주문가능현금', 'type': 'String', 'description': ''},
        {'element': 'ch_uncla', 'label': '현금미수금', 'type': 'String', 'description': ''},
        {'element': 'crd_int_npay_gold', 'label': '신용이자미납금', 'type': 'String', 'description': ''},
        {'element': 'etc_loana', 'label': '기타대여금', 'type': 'String', 'description': ''},
        {'element': 'nrpy_loan', 'label': '미상환융자금', 'type': 'String', 'description': ''},
        {'element': 'profa_ch', 'label': '증거금현금', 'type': 'String', 'description': ''},
        {'element': 'repl_profa', 'label': '증거금대용', 'type': 'String', 'description': ''},
        {'element': 'stk_buy_tot_amt', 'label': '주식매수총액', 'type': 'String', 'description': ''},
        {'element': 'evlt_amt_tot', 'label': '평가금액합계', 'type': 'String', 'description': ''},
        {'element': 'tot_pl_tot', 'label': '총손익합계', 'type': 'String', 'description': ''},
        {'element': 'tot_pl_rt', 'label': '총손익률', 'type': 'String', 'description': ''},
        {'element': 'tot_re_buy_alowa', 'label': '총재매수가능금액', 'type': 'String', 'description': ''},
        {'element': '20ord_alow_amt', 'label': '20%주문가능금액', 'type': 'String', 'description': ''},
        {'element': '30ord_alow_amt', 'label': '30%주문가능금액', 'type': 'String', 'description': ''},
        {'element': '40ord_alow_amt', 'label': '40%주문가능금액', 'type': 'String', 'description': ''},
        {'element': '50ord_alow_amt', 'label': '50%주문가능금액', 'type': 'String', 'description': ''},
        {'element': '60ord_alow_amt', 'label': '60%주문가능금액', 'type': 'String', 'description': ''},
        {'element': '100ord_alow_amt', 'label': '100%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'crd_loan_tot', 'label': '신용융자합계', 'type': 'String', 'description': ''},
        {'element': 'crd_loan_ls_tot', 'label': '신용융자대주합계', 'type': 'String', 'description': ''},
        {'element': 'crd_grnt_rt', 'label': '신용담보비율', 'type': 'String', 'description': ''},
        {'element': 'dpst_grnt_use_amt_amt', 'label': '예탁담보대출금액', 'type': 'String', 'description': ''},
        {'element': 'grnt_loan_amt', 'label': '매도담보대출금액', 'type': 'String', 'description': ''},
        {'element': 'stk_cntr_remn', 'label': '종목별체결잔고', 'type': 'LIST', 'description': ''},
        {'element': '- crd_tp', 'label': '신용구분', 'type': 'String', 'description': ''},
        {'element': '- loan_dt', 'label': '대출일', 'type': 'String', 'description': ''},
        {'element': '- expr_dt', 'label': '만기일', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목번호', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- setl_remn', 'label': '결제잔고', 'type': 'String', 'description': ''},
        {'element': '- cur_qty', 'label': '현재잔고', 'type': 'String', 'description': ''},
        {'element': '- cur_prc', 'label': '현재가', 'type': 'String', 'description': ''},
        {'element': '- buy_uv', 'label': '매입단가', 'type': 'String', 'description': ''},
        {'element': '- pur_amt', 'label': '매입금액', 'type': 'String', 'description': ''},
        {'element': '- evlt_amt', 'label': '평가금액', 'type': 'String', 'description': ''},
        {'element': '- evltv_prft', 'label': '평가손익', 'type': 'String', 'description': ''},
        {'element': '- pl_rt', 'label': '손익률', 'type': 'String', 'description': ''},
    ],
    'kt00007': [
        {'element': 'acnt_ord_cntr_prps_dtl', 'label': '계좌별주문체결내역상세', 'type': 'LIST', 'description': ''},
        {'element': '- ord_no', 'label': '주문번호', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목번호', 'type': 'String', 'description': ''},
        {'element': '- trde_tp', 'label': '매매구분', 'type': 'String', 'description': ''},
        {'element': '- crd_tp', 'label': '신용구분', 'type': 'String', 'description': ''},
        {'element': '- ord_qty', 'label': '주문수량', 'type': 'String', 'description': ''},
        {'element': '- ord_uv', 'label': '주문단가', 'type': 'String', 'description': ''},
        {'element': '- cnfm_qty', 'label': '확인수량', 'type': 'String', 'description': ''},
        {'element': '- acpt_tp', 'label': '접수구분', 'type': 'String', 'description': ''},
        {'element': '- rsrv_tp', 'label': '반대여부', 'type': 'String', 'description': ''},
        {'element': '- ord_tm', 'label': '주문시간', 'type': 'String', 'description': ''},
        {'element': '- ori_ord', 'label': '원주문', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- io_tp_nm', 'label': '주문구분', 'type': 'String', 'description': ''},
        {'element': '- loan_dt', 'label': '대출일', 'type': 'String', 'description': ''},
        {'element': '- cntr_qty', 'label': '체결수량', 'type': 'String', 'description': ''},
        {'element': '- cntr_uv', 'label': '체결단가', 'type': 'String', 'description': ''},
        {'element': '- ord_remnq', 'label': '주문잔량', 'type': 'String', 'description': ''},
        {'element': '- comm_ord_tp', 'label': '통신구분', 'type': 'String', 'description': ''},
        {'element': '- mdfy_cncl', 'label': '정정취소', 'type': 'String', 'description': ''},
        {'element': '- cnfm_tm', 'label': '확인시간', 'type': 'String', 'description': ''},
        {'element': '- dmst_stex_tp', 'label': '국내거래소구분', 'type': 'String', 'description': ''},
        {'element': '- cond_uv', 'label': '스톱가', 'type': 'String', 'description': ''},
    ],
    'kt00008': [
        {'element': 'trde_dt', 'label': '매매일자', 'type': 'String', 'description': ''},
        {'element': 'setl_dt', 'label': '결제일자', 'type': 'String', 'description': ''},
        {'element': 'sell_amt_sum', 'label': '매도정산합', 'type': 'String', 'description': ''},
        {'element': 'buy_amt_sum', 'label': '매수정산합', 'type': 'String', 'description': ''},
        {'element': 'acnt_nxdy_setl_frcs_prps_array', 'label': '계좌별익일결제예정내역배열', 'type': 'LIST', 'description': ''},
        {'element': '- seq', 'label': '일련번호', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목번호', 'type': 'String', 'description': ''},
        {'element': '- loan_dt', 'label': '대출일', 'type': 'String', 'description': ''},
        {'element': '- qty', 'label': '수량', 'type': 'String', 'description': ''},
        {'element': '- engg_amt', 'label': '약정금액', 'type': 'String', 'description': ''},
        {'element': '- cmsn', 'label': '수수료', 'type': 'String', 'description': ''},
        {'element': '- incm_tax', 'label': '소득세', 'type': 'String', 'description': ''},
        {'element': '- rstx', 'label': '농특세', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- sell_tp', 'label': '매도수구분', 'type': 'String', 'description': ''},
        {'element': '- unp', 'label': '단가', 'type': 'String', 'description': ''},
        {'element': '- exct_amt', 'label': '정산금액', 'type': 'String', 'description': ''},
        {'element': '- trde_tax', 'label': '거래세', 'type': 'String', 'description': ''},
        {'element': '- resi_tax', 'label': '주민세', 'type': 'String', 'description': ''},
        {'element': '- crd_tp', 'label': '신용구분', 'type': 'String', 'description': ''},
    ],
    'kt00009': [
        {'element': 'sell_grntl_engg_amt', 'label': '매도약정금액', 'type': 'String', 'description': ''},
        {'element': 'buy_engg_amt', 'label': '매수약정금액', 'type': 'String', 'description': ''},
        {'element': 'engg_amt', 'label': '약정금액', 'type': 'String', 'description': ''},
        {'element': 'acnt_ord_cntr_prst_array', 'label': '계좌별주문체결현황배열', 'type': 'LIST', 'description': ''},
        {'element': '- stk_bond_tp', 'label': '주식채권구분', 'type': 'String', 'description': ''},
        {'element': '- ord_no', 'label': '주문번호', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목번호', 'type': 'String', 'description': ''},
        {'element': '- trde_tp', 'label': '매매구분', 'type': 'String', 'description': ''},
        {'element': '- io_tp_nm', 'label': '주문유형구분', 'type': 'String', 'description': ''},
        {'element': '- ord_qty', 'label': '주문수량', 'type': 'String', 'description': ''},
        {'element': '- ord_uv', 'label': '주문단가', 'type': 'String', 'description': ''},
        {'element': '- cnfm_qty', 'label': '확인수량', 'type': 'String', 'description': ''},
        {'element': '- rsrv_oppo', 'label': '예약/반대', 'type': 'String', 'description': ''},
        {'element': '- cntr_no', 'label': '체결번호', 'type': 'String', 'description': ''},
        {'element': '- acpt_tp', 'label': '접수구분', 'type': 'String', 'description': ''},
        {'element': '- orig_ord_no', 'label': '원주문번호', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- setl_tp', 'label': '결제구분', 'type': 'String', 'description': ''},
        {'element': '- crd_deal_tp', 'label': '신용거래구분', 'type': 'String', 'description': ''},
        {'element': '- cntr_qty', 'label': '체결수량', 'type': 'String', 'description': ''},
        {'element': '- cntr_uv', 'label': '체결단가', 'type': 'String', 'description': ''},
        {'element': '- comm_ord_tp', 'label': '통신구분', 'type': 'String', 'description': ''},
        {'element': '- mdfy_cncl_tp', 'label': '정정/취소구분', 'type': 'String', 'description': ''},
        {'element': '- cntr_tm', 'label': '체결시간', 'type': 'String', 'description': ''},
        {'element': '- dmst_stex_tp', 'label': '국내거래소구분', 'type': 'String', 'description': ''},
        {'element': '- cond_uv', 'label': '스톱가', 'type': 'String', 'description': ''},
    ],
    'kt00010': [
        {'element': 'profa_20ord_alow_amt', 'label': '증거금20%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_20ord_alowq', 'label': '증거금20%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'profa_30ord_alow_amt', 'label': '증거금30%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_30ord_alowq', 'label': '증거금30%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'profa_40ord_alow_amt', 'label': '증거금40%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_40ord_alowq', 'label': '증거금40%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'profa_50ord_alow_amt', 'label': '증거금50%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_50ord_alowq', 'label': '증거금50%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'profa_60ord_alow_amt', 'label': '증거금60%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_60ord_alowq', 'label': '증거금60%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'profa_rdex_60ord_alow_amt', 'label': '증거금감면60%주문가능금', 'type': 'String', 'description': ''},
        {'element': 'profa_rdex_60ord_alowq', 'label': '증거금감면60%주문가능수', 'type': 'String', 'description': ''},
        {'element': 'profa_100ord_alow_amt', 'label': '증거금100%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_100ord_alowq', 'label': '증거금100%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'pred_reu_alowa', 'label': '전일재사용가능금액', 'type': 'String', 'description': ''},
        {'element': 'tdy_reu_alowa', 'label': '금일재사용가능금액', 'type': 'String', 'description': ''},
        {'element': 'entr', 'label': '예수금', 'type': 'String', 'description': ''},
        {'element': 'repl_amt', 'label': '대용금', 'type': 'String', 'description': ''},
        {'element': 'uncla', 'label': '미수금', 'type': 'String', 'description': ''},
        {'element': 'ord_pos_repl', 'label': '주문가능대용', 'type': 'String', 'description': ''},
        {'element': 'ord_alowa', 'label': '주문가능현금', 'type': 'String', 'description': ''},
        {'element': 'wthd_alowa', 'label': '인출가능금액', 'type': 'String', 'description': ''},
        {'element': 'nxdy_wthd_alowa', 'label': '익일인출가능금액', 'type': 'String', 'description': ''},
        {'element': 'pur_amt', 'label': '매입금액', 'type': 'String', 'description': ''},
        {'element': 'cmsn', 'label': '수수료', 'type': 'String', 'description': ''},
        {'element': 'pur_exct_amt', 'label': '매입정산금', 'type': 'String', 'description': ''},
        {'element': 'd2entra', 'label': 'D2추정예수금', 'type': 'String', 'description': ''},
        {'element': 'profa_rdex_aplc_tp', 'label': '증거금감면적용구분', 'type': 'String', 'description': '0:일반,1:60%감면'},
    ],
    'kt00011': [
        {'element': 'stk_profa_rt', 'label': '종목증거금율', 'type': 'String', 'description': ''},
        {'element': 'profa_rt', 'label': '계좌증거금율', 'type': 'String', 'description': ''},
        {'element': 'aplc_rt', 'label': '적용증거금율', 'type': 'String', 'description': ''},
        {'element': 'profa_20ord_alow_amt', 'label': '증거금20%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_20ord_alowq', 'label': '증거금20%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'profa_20pred_reu_amt', 'label': '증거금20%전일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'profa_20tdy_reu_amt', 'label': '증거금20%금일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'profa_30ord_alow_amt', 'label': '증거금30%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_30ord_alowq', 'label': '증거금30%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'profa_30pred_reu_amt', 'label': '증거금30%전일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'profa_30tdy_reu_amt', 'label': '증거금30%금일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'profa_40ord_alow_amt', 'label': '증거금40%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_40ord_alowq', 'label': '증거금40%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'profa_40pred_reu_amt', 'label': '증거금40전일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'profa_40tdy_reu_amt', 'label': '증거금40%금일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'profa_50ord_alow_amt', 'label': '증거금50%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_50ord_alowq', 'label': '증거금50%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'profa_50pred_reu_amt', 'label': '증거금50%전일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'profa_50tdy_reu_amt', 'label': '증거금50%금일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'profa_60ord_alow_amt', 'label': '증거금60%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_60ord_alowq', 'label': '증거금60%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'profa_60pred_reu_amt', 'label': '증거금60%전일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'profa_60tdy_reu_amt', 'label': '증거금60%금일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'profa_100ord_alow_amt', 'label': '증거금100%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'profa_100ord_alowq', 'label': '증거금100%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'profa_100pred_reu_amt', 'label': '증거금100%전일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'profa_100tdy_reu_amt', 'label': '증거금100%금일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'min_ord_alow_amt', 'label': '미수불가주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'min_ord_alowq', 'label': '미수불가주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'min_pred_reu_amt', 'label': '미수불가전일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'min_tdy_reu_amt', 'label': '미수불가금일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'entr', 'label': '예수금', 'type': 'String', 'description': ''},
        {'element': 'repl_amt', 'label': '대용금', 'type': 'String', 'description': ''},
        {'element': 'uncla', 'label': '미수금', 'type': 'String', 'description': ''},
        {'element': 'ord_pos_repl', 'label': '주문가능대용', 'type': 'String', 'description': ''},
        {'element': 'ord_alowa', 'label': '주문가능현금', 'type': 'String', 'description': ''},
    ],
    'kt00012': [
        {'element': 'stk_assr_rt', 'label': '종목보증금율', 'type': 'String', 'description': ''},
        {'element': 'stk_assr_rt_nm', 'label': '종목보증금율명', 'type': 'String', 'description': ''},
        {'element': 'assr_30ord_alow_amt', 'label': '보증금30%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'assr_30ord_alowq', 'label': '보증금30%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'assr_30pred_reu_amt', 'label': '보증금30%전일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'assr_30tdy_reu_amt', 'label': '보증금30%금일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'assr_40ord_alow_amt', 'label': '보증금40%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'assr_40ord_alowq', 'label': '보증금40%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'assr_40pred_reu_amt', 'label': '보증금40%전일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'assr_40tdy_reu_amt', 'label': '보증금40%금일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'assr_50ord_alow_amt', 'label': '보증금50%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'assr_50ord_alowq', 'label': '보증금50%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'assr_50pred_reu_amt', 'label': '보증금50%전일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'assr_50tdy_reu_amt', 'label': '보증금50%금일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'assr_60ord_alow_amt', 'label': '보증금60%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'assr_60ord_alowq', 'label': '보증금60%주문가능수량', 'type': 'String', 'description': ''},
        {'element': 'assr_60pred_reu_amt', 'label': '보증금60%전일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'assr_60tdy_reu_amt', 'label': '보증금60%금일재사용금액', 'type': 'String', 'description': ''},
        {'element': 'entr', 'label': '예수금', 'type': 'String', 'description': ''},
        {'element': 'repl_amt', 'label': '대용금', 'type': 'String', 'description': ''},
        {'element': 'uncla', 'label': '미수금', 'type': 'String', 'description': ''},
        {'element': 'ord_pos_repl', 'label': '주문가능대용', 'type': 'String', 'description': ''},
        {'element': 'ord_alowa', 'label': '주문가능현금', 'type': 'String', 'description': ''},
        {'element': 'out_alowa', 'label': '미수가능금액', 'type': 'String', 'description': ''},
        {'element': 'out_pos_qty', 'label': '미수가능수량', 'type': 'String', 'description': ''},
        {'element': 'min_amt', 'label': '미수불가금액', 'type': 'String', 'description': ''},
        {'element': 'min_qty', 'label': '미수불가수량', 'type': 'String', 'description': ''},
    ],
    'kt00013': [
        {'element': 'tdy_reu_objt_amt', 'label': '금일재사용대상금액', 'type': 'String', 'description': ''},
        {'element': 'tdy_reu_use_amt', 'label': '금일재사용사용금액', 'type': 'String', 'description': ''},
        {'element': 'tdy_reu_alowa', 'label': '금일재사용가능금액', 'type': 'String', 'description': ''},
        {'element': 'tdy_reu_lmtt_amt', 'label': '금일재사용제한금액', 'type': 'String', 'description': ''},
        {'element': 'tdy_reu_alowa_fin', 'label': '금일재사용가능금액최종', 'type': 'String', 'description': ''},
        {'element': 'pred_reu_objt_amt', 'label': '전일재사용대상금액', 'type': 'String', 'description': ''},
        {'element': 'pred_reu_use_amt', 'label': '전일재사용사용금액', 'type': 'String', 'description': ''},
        {'element': 'pred_reu_alowa', 'label': '전일재사용가능금액', 'type': 'String', 'description': ''},
        {'element': 'pred_reu_lmtt_amt', 'label': '전일재사용제한금액', 'type': 'String', 'description': ''},
        {'element': 'pred_reu_alowa_fin', 'label': '전일재사용가능금액최종', 'type': 'String', 'description': ''},
        {'element': 'ch_amt', 'label': '현금금액', 'type': 'String', 'description': ''},
        {'element': 'ch_profa', 'label': '현금증거금', 'type': 'String', 'description': ''},
        {'element': 'use_pos_ch', 'label': '사용가능현금', 'type': 'String', 'description': ''},
        {'element': 'ch_use_lmtt_amt', 'label': '현금사용제한금액', 'type': 'String', 'description': ''},
        {'element': 'use_pos_ch_fin', 'label': '사용가능현금최종', 'type': 'String', 'description': ''},
        {'element': 'repl_amt_amt', 'label': '대용금액', 'type': 'String', 'description': ''},
        {'element': 'repl_profa', 'label': '대용증거금', 'type': 'String', 'description': ''},
        {'element': 'use_pos_repl', 'label': '사용가능대용', 'type': 'String', 'description': ''},
        {'element': 'repl_use_lmtt_amt', 'label': '대용사용제한금액', 'type': 'String', 'description': ''},
        {'element': 'use_pos_repl_fin', 'label': '사용가능대용최종', 'type': 'String', 'description': ''},
        {'element': 'crd_grnta_ch', 'label': '신용보증금현금', 'type': 'String', 'description': ''},
        {'element': 'crd_grnta_repl', 'label': '신용보증금대용', 'type': 'String', 'description': ''},
        {'element': 'crd_grnt_ch', 'label': '신용담보금현금', 'type': 'String', 'description': ''},
        {'element': 'crd_grnt_repl', 'label': '신용담보금대용', 'type': 'String', 'description': ''},
        {'element': 'uncla', 'label': '미수금', 'type': 'String', 'description': ''},
        {'element': 'ls_grnt_reu_gold', 'label': '대주담보금재사용금', 'type': 'String', 'description': ''},
        {'element': '20ord_alow_amt', 'label': '20%주문가능금액', 'type': 'String', 'description': ''},
        {'element': '30ord_alow_amt', 'label': '30%주문가능금액', 'type': 'String', 'description': ''},
        {'element': '40ord_alow_amt', 'label': '40%주문가능금액', 'type': 'String', 'description': ''},
        {'element': '50ord_alow_amt', 'label': '50%주문가능금액', 'type': 'String', 'description': ''},
        {'element': '60ord_alow_amt', 'label': '60%주문가능금액', 'type': 'String', 'description': ''},
        {'element': '100ord_alow_amt', 'label': '100%주문가능금액', 'type': 'String', 'description': ''},
        {'element': 'tdy_crd_rpya_loss_amt', 'label': '금일신용상환손실금액', 'type': 'String', 'description': ''},
        {'element': 'pred_crd_rpya_loss_amt', 'label': '전일신용상환손실금액', 'type': 'String', 'description': ''},
        {'element': 'tdy_ls_rpya_loss_repl_profa', 'label': '금일대주상환손실대용증거금', 'type': 'String', 'description': ''},
        {'element': 'pred_ls_rpya_loss_repl_profa', 'label': '전일대주상환손실대용증거금', 'type': 'String', 'description': ''},
        {'element': 'evlt_repl_amt_spg_use_skip', 'label': '평가대용금(현물사용제외)', 'type': 'String', 'description': ''},
        {'element': 'evlt_repl_rt', 'label': '평가대용비율', 'type': 'String', 'description': ''},
        {'element': 'crd_repl_profa', 'label': '신용대용증거금', 'type': 'String', 'description': ''},
        {'element': 'ch_ord_repl_profa', 'label': '현금주문대용증거금', 'type': 'String', 'description': ''},
        {'element': 'crd_ord_repl_profa', 'label': '신용주문대용증거금', 'type': 'String', 'description': ''},
        {'element': 'crd_repl_conv_gold', 'label': '신용대용환산금', 'type': 'String', 'description': ''},
        {'element': 'repl_alowa', 'label': '대용가능금액(현금제한)', 'type': 'String', 'description': ''},
        {'element': 'repl_alowa_2', 'label': '대용가능금액2(신용제한)', 'type': 'String', 'description': ''},
        {'element': 'ch_repl_lck_gold', 'label': '현금대용부족금', 'type': 'String', 'description': ''},
        {'element': 'crd_repl_lck_gold', 'label': '신용대용부족금', 'type': 'String', 'description': ''},
        {'element': 'ch_ord_alow_repla', 'label': '현금주문가능대용금', 'type': 'String', 'description': ''},
        {'element': 'crd_ord_alow_repla', 'label': '신용주문가능대용금', 'type': 'String', 'description': ''},
        {'element': 'd2vexct_entr', 'label': 'D2가정산예수금', 'type': 'String', 'description': ''},
        {'element': 'd2ch_ord_alow_amt', 'label': 'D2현금주문가능금액', 'type': 'String', 'description': ''},
    ],
    'kt00015': [
        {'element': 'trst_ovrl_trde_prps_array', 'label': '위탁종합거래내역배열', 'type': 'LIST', 'description': ''},
        {'element': '- trde_dt', 'label': '거래일자', 'type': 'String', 'description': ''},
        {'element': '- trde_no', 'label': '거래번호', 'type': 'String', 'description': ''},
        {'element': '- rmrk_nm', 'label': '적요명', 'type': 'String', 'description': ''},
        {'element': '- crd_deal_tp_nm', 'label': '신용거래구분명', 'type': 'String', 'description': ''},
        {'element': '- exct_amt', 'label': '정산금액', 'type': 'String', 'description': ''},
        {'element': '- loan_amt_rpya', 'label': '대출금상환', 'type': 'String', 'description': ''},
        {'element': '- fc_trde_amt', 'label': '거래금액(외)', 'type': 'String', 'description': ''},
        {'element': '- fc_exct_amt', 'label': '정산금액(외)', 'type': 'String', 'description': ''},
        {'element': '- entra_remn', 'label': '예수금잔고', 'type': 'String', 'description': ''},
        {'element': '- crnc_cd', 'label': '통화코드', 'type': 'String', 'description': ''},
        {'element': '- trde_ocr_tp', 'label': '거래종류구분', 'type': 'String', 'description': '1:입출금, 2:펀드, 3:ELS, 4:채권, 5:해외채권, 6:외화RP, 7:외화발행어음'},
        {'element': '- trde_kind_nm', 'label': '거래종류명', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- trde_amt', 'label': '거래금액', 'type': 'String', 'description': ''},
        {'element': '- trde_agri_tax', 'label': '거래및농특세', 'type': 'String', 'description': ''},
        {'element': '- rpy_diffa', 'label': '상환차금', 'type': 'String', 'description': ''},
        {'element': '- fc_trde_tax', 'label': '거래세(외)', 'type': 'String', 'description': ''},
        {'element': '- dly_sum', 'label': '연체합', 'type': 'String', 'description': ''},
        {'element': '- fc_entra', 'label': '외화예수금잔고', 'type': 'String', 'description': ''},
        {'element': '- mdia_tp_nm', 'label': '매체구분명', 'type': 'String', 'description': ''},
        {'element': '- io_tp', 'label': '입출구분', 'type': 'String', 'description': ''},
        {'element': '- io_tp_nm', 'label': '입출구분명', 'type': 'String', 'description': ''},
        {'element': '- orig_deal_no', 'label': '원거래번호', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
        {'element': '- trde_qty_jwa_cnt', 'label': '거래수량/좌수', 'type': 'String', 'description': ''},
        {'element': '- cmsn', 'label': '수수료', 'type': 'String', 'description': ''},
        {'element': '- int_ls_usfe', 'label': '이자/대주이용', 'type': 'String', 'description': ''},
        {'element': '- fc_cmsn', 'label': '수수료(외)', 'type': 'String', 'description': ''},
        {'element': '- fc_dly_sum', 'label': '연체합(외)', 'type': 'String', 'description': ''},
        {'element': '- vlbl_nowrm', 'label': '유가금잔', 'type': 'String', 'description': ''},
        {'element': '- proc_tm', 'label': '처리시간', 'type': 'String', 'description': ''},
        {'element': '- isin_cd', 'label': 'ISIN코드', 'type': 'String', 'description': ''},
        {'element': '- stex_cd', 'label': '거래소코드', 'type': 'String', 'description': ''},
        {'element': '- stex_nm', 'label': '거래소명', 'type': 'String', 'description': ''},
        {'element': '- trde_unit', 'label': '거래단가/환율', 'type': 'String', 'description': ''},
        {'element': '- incm_resi_tax', 'label': '소득/주민세', 'type': 'String', 'description': ''},
        {'element': '- loan_dt', 'label': '대출일', 'type': 'String', 'description': ''},
        {'element': '- uncl_ocr', 'label': '미수(원/주)', 'type': 'String', 'description': ''},
        {'element': '- rpym_sum', 'label': '변제합', 'type': 'String', 'description': ''},
        {'element': '- cntr_dt', 'label': '체결일', 'type': 'String', 'description': ''},
        {'element': '- rcpy_no', 'label': '출납번호', 'type': 'String', 'description': ''},
        {'element': '- prcsr', 'label': '처리자', 'type': 'String', 'description': ''},
        {'element': '- proc_brch', 'label': '처리점', 'type': 'String', 'description': ''},
        {'element': '- trde_stle', 'label': '매매형태', 'type': 'String', 'description': ''},
        {'element': '- txon_base_pric', 'label': '과세기준가', 'type': 'String', 'description': ''},
        {'element': '- tax_sum_cmsn', 'label': '세금수수료합', 'type': 'String', 'description': ''},
        {'element': '- frgn_pay_txam', 'label': '외국납부세액(외)', 'type': 'String', 'description': ''},
        {'element': '- fc_uncl_ocr', 'label': '미수(외)', 'type': 'String', 'description': ''},
        {'element': '- rpym_sum_fr', 'label': '변제합(외)', 'type': 'String', 'description': ''},
        {'element': '- rcpmnyer', 'label': '입금자', 'type': 'String', 'description': ''},
        {'element': '- trde_prtc_tp', 'label': '거래내역구분', 'type': 'String', 'description': ''},
    ],
    'kt00016': [
        {'element': 'mang_empno', 'label': '관리사원번호', 'type': 'String', 'description': ''},
        {'element': 'mngr_nm', 'label': '관리자명', 'type': 'String', 'description': ''},
        {'element': 'dept_nm', 'label': '관리자지점', 'type': 'String', 'description': ''},
        {'element': 'entr_fr', 'label': '예수금_초', 'type': 'String', 'description': ''},
        {'element': 'entr_to', 'label': '예수금_말', 'type': 'String', 'description': ''},
        {'element': 'scrt_evlt_amt_fr', 'label': '유가증권평가금액_초', 'type': 'String', 'description': ''},
        {'element': 'scrt_evlt_amt_to', 'label': '유가증권평가금액_말', 'type': 'String', 'description': ''},
        {'element': 'ls_grnt_fr', 'label': '대주담보금_초', 'type': 'String', 'description': ''},
        {'element': 'ls_grnt_to', 'label': '대주담보금_말', 'type': 'String', 'description': ''},
        {'element': 'crd_loan_fr', 'label': '신용융자금_초', 'type': 'String', 'description': ''},
        {'element': 'crd_loan_to', 'label': '신용융자금_말', 'type': 'String', 'description': ''},
        {'element': 'ch_uncla_fr', 'label': '현금미수금_초', 'type': 'String', 'description': ''},
        {'element': 'ch_uncla_to', 'label': '현금미수금_말', 'type': 'String', 'description': ''},
        {'element': 'krw_asgna_fr', 'label': '원화대용금_초', 'type': 'String', 'description': ''},
        {'element': 'krw_asgna_to', 'label': '원화대용금_말', 'type': 'String', 'description': ''},
        {'element': 'ls_evlta_fr', 'label': '대주평가금_초', 'type': 'String', 'description': ''},
        {'element': 'ls_evlta_to', 'label': '대주평가금_말', 'type': 'String', 'description': ''},
        {'element': 'rght_evlta_fr', 'label': '권리평가금_초', 'type': 'String', 'description': ''},
        {'element': 'rght_evlta_to', 'label': '권리평가금_말', 'type': 'String', 'description': ''},
        {'element': 'loan_amt_fr', 'label': '대출금_초', 'type': 'String', 'description': ''},
        {'element': 'loan_amt_to', 'label': '대출금_말', 'type': 'String', 'description': ''},
        {'element': 'etc_loana_fr', 'label': '기타대여금_초', 'type': 'String', 'description': ''},
        {'element': 'etc_loana_to', 'label': '기타대여금_말', 'type': 'String', 'description': ''},
        {'element': 'crd_int_npay_gold_fr', 'label': '신용이자미납금_초', 'type': 'String', 'description': ''},
        {'element': 'crd_int_npay_gold_to', 'label': '신용이자미납금_말', 'type': 'String', 'description': ''},
        {'element': 'crd_int_fr', 'label': '신용이자_초', 'type': 'String', 'description': ''},
        {'element': 'crd_int_to', 'label': '신용이자_말', 'type': 'String', 'description': ''},
        {'element': 'tot_amt_fr', 'label': '순자산액계_초', 'type': 'String', 'description': ''},
        {'element': 'tot_amt_to', 'label': '순자산액계_말', 'type': 'String', 'description': ''},
        {'element': 'invt_bsamt', 'label': '투자원금평잔', 'type': 'String', 'description': ''},
        {'element': 'evltv_prft', 'label': '평가손익', 'type': 'String', 'description': ''},
        {'element': 'prft_rt', 'label': '수익률', 'type': 'String', 'description': ''},
        {'element': 'tern_rt', 'label': '회전율', 'type': 'String', 'description': ''},
        {'element': 'termin_tot_trns', 'label': '기간내총입금', 'type': 'String', 'description': ''},
        {'element': 'termin_tot_pymn', 'label': '기간내총출금', 'type': 'String', 'description': ''},
        {'element': 'termin_tot_inq', 'label': '기간내총입고', 'type': 'String', 'description': ''},
        {'element': 'termin_tot_outq', 'label': '기간내총출고', 'type': 'String', 'description': ''},
        {'element': 'futr_repl_sella', 'label': '선물대용매도금액', 'type': 'String', 'description': ''},
        {'element': 'trst_repl_sella', 'label': '위탁대용매도금액', 'type': 'String', 'description': ''},
    ],
    'kt00017': [
        {'element': 'd2_entra', 'label': 'D+2추정예수금', 'type': 'String', 'description': ''},
        {'element': 'crd_int_npay_gold', 'label': '신용이자미납금', 'type': 'String', 'description': ''},
        {'element': 'etc_loana', 'label': '기타대여금', 'type': 'String', 'description': ''},
        {'element': 'gnrl_stk_evlt_amt_d2', 'label': '일반주식평가금액D+2', 'type': 'String', 'description': ''},
        {'element': 'dpst_grnt_use_amt_d2', 'label': '예탁담보대출금D+2', 'type': 'String', 'description': ''},
        {'element': 'crd_stk_evlt_amt_d2', 'label': '예탁담보주식평가금액D+2', 'type': 'String', 'description': ''},
        {'element': 'crd_loan_d2', 'label': '신용융자금D+2', 'type': 'String', 'description': ''},
        {'element': 'crd_loan_evlta_d2', 'label': '신용융자평가금D+2', 'type': 'String', 'description': ''},
        {'element': 'crd_ls_grnt_d2', 'label': '신용대주담보금D+2', 'type': 'String', 'description': ''},
        {'element': 'crd_ls_evlta_d2', 'label': '신용대주평가금D+2', 'type': 'String', 'description': ''},
        {'element': 'ina_amt', 'label': '입금금액', 'type': 'String', 'description': ''},
        {'element': 'outa', 'label': '출금금액', 'type': 'String', 'description': ''},
        {'element': 'inq_amt', 'label': '입고금액', 'type': 'String', 'description': ''},
        {'element': 'outq_amt', 'label': '출고금액', 'type': 'String', 'description': ''},
        {'element': 'sell_amt', 'label': '매도금액', 'type': 'String', 'description': ''},
        {'element': 'buy_amt', 'label': '매수금액', 'type': 'String', 'description': ''},
        {'element': 'cmsn', 'label': '수수료', 'type': 'String', 'description': ''},
        {'element': 'tax', 'label': '세금', 'type': 'String', 'description': ''},
        {'element': 'stk_pur_cptal_loan_amt', 'label': '주식매입자금대출금', 'type': 'String', 'description': ''},
        {'element': 'rp_evlt_amt', 'label': 'RP평가금액', 'type': 'String', 'description': ''},
        {'element': 'bd_evlt_amt', 'label': '채권평가금액', 'type': 'String', 'description': ''},
        {'element': 'elsevlt_amt', 'label': 'ELS평가금액', 'type': 'String', 'description': ''},
        {'element': 'crd_int_amt', 'label': '신용이자금액', 'type': 'String', 'description': ''},
        {'element': 'sel_prica_grnt_loan_int_amt_amt', 'label': '매도대금담보대출이자금액', 'type': 'String', 'description': ''},
        {'element': 'dvida_amt', 'label': '배당금액', 'type': 'String', 'description': ''},
    ],
    'kt00018': [
        {'element': 'tot_pur_amt', 'label': '총매입금액', 'type': 'String', 'description': ''},
        {'element': 'tot_evlt_amt', 'label': '총평가금액', 'type': 'String', 'description': ''},
        {'element': 'tot_evlt_pl', 'label': '총평가손익금액', 'type': 'String', 'description': ''},
        {'element': 'tot_prft_rt', 'label': '총수익률(%)', 'type': 'String', 'description': ''},
        {'element': 'prsm_dpst_aset_amt', 'label': '추정예탁자산', 'type': 'String', 'description': ''},
        {'element': 'tot_loan_amt', 'label': '총대출금', 'type': 'String', 'description': ''},
        {'element': 'tot_crd_loan_amt', 'label': '총융자금액', 'type': 'String', 'description': ''},
        {'element': 'tot_crd_ls_amt', 'label': '총대주금액', 'type': 'String', 'description': ''},
        {'element': 'acnt_evlt_remn_indv_tot', 'label': '계좌평가잔고개별합산', 'type': 'LIST', 'description': ''},
        {'element': '- stk_cd', 'label': '종목번호', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- evltv_prft', 'label': '평가손익', 'type': 'String', 'description': ''},
        {'element': '- prft_rt', 'label': '수익률(%)', 'type': 'String', 'description': ''},
        {'element': '- pur_pric', 'label': '매입가', 'type': 'String', 'description': ''},
        {'element': '- pred_close_pric', 'label': '전일종가', 'type': 'String', 'description': ''},
        {'element': '- rmnd_qty', 'label': '보유수량', 'type': 'String', 'description': ''},
        {'element': '- trde_able_qty', 'label': '매매가능수량', 'type': 'String', 'description': ''},
        {'element': '- cur_prc', 'label': '현재가', 'type': 'String', 'description': ''},
        {'element': '- pred_buyq', 'label': '전일매수수량', 'type': 'String', 'description': ''},
        {'element': '- pred_sellq', 'label': '전일매도수량', 'type': 'String', 'description': ''},
        {'element': '- tdy_buyq', 'label': '금일매수수량', 'type': 'String', 'description': ''},
        {'element': '- tdy_sellq', 'label': '금일매도수량', 'type': 'String', 'description': ''},
        {'element': '- pur_amt', 'label': '매입금액', 'type': 'String', 'description': ''},
        {'element': '- pur_cmsn', 'label': '매입수수료', 'type': 'String', 'description': ''},
        {'element': '- evlt_amt', 'label': '평가금액', 'type': 'String', 'description': ''},
        {'element': '- sell_cmsn', 'label': '평가수수료', 'type': 'String', 'description': ''},
        {'element': '- tax', 'label': '세금', 'type': 'String', 'description': ''},
        {'element': '- sum_cmsn', 'label': '수수료합', 'type': 'String', 'description': '매입수수료 + 평가수수료'},
        {'element': '- poss_rt', 'label': '보유비중(%)', 'type': 'String', 'description': ''},
        {'element': '- crd_tp', 'label': '신용구분', 'type': 'String', 'description': ''},
        {'element': '- crd_tp_nm', 'label': '신용구분명', 'type': 'String', 'description': ''},
        {'element': '- crd_loan_dt', 'label': '대출일', 'type': 'String', 'description': ''},
    ],
    'kt50020': [
        {'element': 'tot_entr', 'label': '예수금', 'type': 'String', 'description': ''},
        {'element': 'net_entr', 'label': '추정예수금', 'type': 'String', 'description': ''},
        {'element': 'tot_est_amt', 'label': '잔고평가액', 'type': 'String', 'description': ''},
        {'element': 'net_amt', 'label': '예탁자산평가액', 'type': 'String', 'description': ''},
        {'element': 'tot_book_amt2', 'label': '총매입금액', 'type': 'String', 'description': ''},
        {'element': 'tot_dep_amt', 'label': '추정예탁자산', 'type': 'String', 'description': ''},
        {'element': 'paym_alowa', 'label': '출금가능금액', 'type': 'String', 'description': ''},
        {'element': 'pl_amt', 'label': '실현손익', 'type': 'String', 'description': ''},
        {'element': 'gold_acnt_evlt_prst', 'label': '금현물계좌평가현황', 'type': 'LIST', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- real_qty', 'label': '보유수량', 'type': 'String', 'description': ''},
        {'element': '- avg_prc', 'label': '평균단가', 'type': 'String', 'description': ''},
        {'element': '- cur_prc', 'label': '현재가', 'type': 'String', 'description': ''},
        {'element': '- est_amt', 'label': '평가금액', 'type': 'String', 'description': ''},
        {'element': '- est_lspft', 'label': '손익금액', 'type': 'String', 'description': ''},
        {'element': '- est_ratio', 'label': '손익율', 'type': 'String', 'description': ''},
        {'element': '- cmsn', 'label': '수수료', 'type': 'String', 'description': ''},
        {'element': '- vlad_tax', 'label': '부가가치세', 'type': 'String', 'description': ''},
        {'element': '- book_amt2', 'label': '매입금액', 'type': 'String', 'description': ''},
        {'element': '- pl_prch_prc', 'label': '손익분기매입가', 'type': 'String', 'description': ''},
        {'element': '- qty', 'label': '결제잔고', 'type': 'String', 'description': ''},
        {'element': '- buy_qty', 'label': '매수수량', 'type': 'String', 'description': ''},
        {'element': '- sell_qty', 'label': '매도수량', 'type': 'String', 'description': ''},
        {'element': '- able_qty', 'label': '가능수량', 'type': 'String', 'description': ''},
    ],
    'kt50021': [
        {'element': 'entra', 'label': '예수금', 'type': 'String', 'description': ''},
        {'element': 'profa_ch', 'label': '증거금현금', 'type': 'String', 'description': ''},
        {'element': 'chck_ina_amt', 'label': '수표입금액', 'type': 'String', 'description': ''},
        {'element': 'etc_loan', 'label': '기타대여금', 'type': 'String', 'description': ''},
        {'element': 'etc_loan_dlfe', 'label': '기타대여금연체료', 'type': 'String', 'description': ''},
        {'element': 'etc_loan_tot', 'label': '기타대여금합계', 'type': 'String', 'description': ''},
        {'element': 'prsm_entra', 'label': '추정예수금', 'type': 'String', 'description': ''},
        {'element': 'buy_exct_amt', 'label': '매수정산금', 'type': 'String', 'description': ''},
        {'element': 'sell_exct_amt', 'label': '매도정산금', 'type': 'String', 'description': ''},
        {'element': 'sell_buy_exct_amt', 'label': '매도매수정산금', 'type': 'String', 'description': ''},
        {'element': 'dly_amt', 'label': '미수변제소요금', 'type': 'String', 'description': ''},
        {'element': 'prsm_pymn_alow_amt', 'label': '추정출금가능금액', 'type': 'String', 'description': ''},
        {'element': 'pymn_alow_amt', 'label': '출금가능금액', 'type': 'String', 'description': ''},
        {'element': 'ord_alow_amt', 'label': '주문가능금액', 'type': 'String', 'description': ''},
    ],
    'kt50030': [
        {'element': 'acnt_ord_cntr_prst', 'label': '계좌별주문체결현황', 'type': 'LIST', 'description': ''},
        {'element': '- stk_bond_tp', 'label': '주식채권구분', 'type': 'String', 'description': ''},
        {'element': '- ord_no', 'label': '주문번호', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '상품코드', 'type': 'String', 'description': ''},
        {'element': '- trde_tp', 'label': '매매구분', 'type': 'String', 'description': ''},
        {'element': '- io_tp_nm', 'label': '주문유형구분', 'type': 'String', 'description': ''},
        {'element': '- ord_qty', 'label': '주문수량', 'type': 'String', 'description': ''},
        {'element': '- ord_uv', 'label': '주문단가', 'type': 'String', 'description': ''},
        {'element': '- cnfm_qty', 'label': '확인수량', 'type': 'String', 'description': ''},
        {'element': '- data_send_end_tp', 'label': '접수구분', 'type': 'String', 'description': ''},
        {'element': '- mrkt_deal_tp', 'label': '시장구분', 'type': 'String', 'description': ''},
        {'element': '- rsrv_tp', 'label': '예약/반대여부', 'type': 'String', 'description': ''},
        {'element': '- orig_ord_no', 'label': '원주문번호', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- dcd_tp_nm', 'label': '결제구분', 'type': 'String', 'description': ''},
        {'element': '- crd_deal_tp', 'label': '신용거래구분', 'type': 'String', 'description': ''},
        {'element': '- cntr_qty', 'label': '체결수량', 'type': 'String', 'description': ''},
        {'element': '- cntr_uv', 'label': '체결단가', 'type': 'String', 'description': ''},
        {'element': '- ord_remnq', 'label': '미체결수량', 'type': 'String', 'description': ''},
        {'element': '- comm_ord_tp', 'label': '통신구분', 'type': 'String', 'description': ''},
        {'element': '- mdfy_cncl_tp', 'label': '정정취소구분', 'type': 'String', 'description': ''},
        {'element': '- dmst_stex_tp', 'label': '국내거래소구분', 'type': 'String', 'description': ''},
        {'element': '- cond_uv', 'label': '스톱가', 'type': 'String', 'description': ''},
    ],
    'kt50031': [
        {'element': 'acnt_ord_cntr_prps_dtl', 'label': '계좌별주문체결내역상세', 'type': 'LIST', 'description': ''},
        {'element': '- ord_no', 'label': '주문번호', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목번호', 'type': 'String', 'description': ''},
        {'element': '- trde_tp', 'label': '매매구분', 'type': 'String', 'description': ''},
        {'element': '- crd_tp', 'label': '신용구분', 'type': 'String', 'description': ''},
        {'element': '- ord_qty', 'label': '주문수량', 'type': 'String', 'description': ''},
        {'element': '- ord_uv', 'label': '주문단가', 'type': 'String', 'description': ''},
        {'element': '- cnfm_qty', 'label': '확인수량', 'type': 'String', 'description': ''},
        {'element': '- acpt_tp', 'label': '접수구분', 'type': 'String', 'description': ''},
        {'element': '- rsrv_tp', 'label': '반대여부', 'type': 'String', 'description': ''},
        {'element': '- ord_tm', 'label': '주문시간', 'type': 'String', 'description': ''},
        {'element': '- ori_ord', 'label': '원주문', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- io_tp_nm', 'label': '주문구분', 'type': 'String', 'description': ''},
        {'element': '- loan_dt', 'label': '대출일', 'type': 'String', 'description': ''},
        {'element': '- cntr_qty', 'label': '체결수량', 'type': 'String', 'description': ''},
        {'element': '- cntr_uv', 'label': '체결단가', 'type': 'String', 'description': ''},
        {'element': '- ord_remnq', 'label': '주문잔량', 'type': 'String', 'description': ''},
        {'element': '- comm_ord_tp', 'label': '통신구분', 'type': 'String', 'description': ''},
        {'element': '- mdfy_cncl', 'label': '정정취소', 'type': 'String', 'description': ''},
        {'element': '- cnfm_tm', 'label': '확인시간', 'type': 'String', 'description': ''},
        {'element': '- dmst_stex_tp', 'label': '국내거래소구분', 'type': 'String', 'description': ''},
        {'element': '- cond_uv', 'label': '스톱가', 'type': 'String', 'description': ''},
    ],
    'kt50032': [
        {'element': 'acnt_print', 'label': '계좌번호', 'type': 'String', 'description': '계좌번호 출력용'},
        {'element': 'gold_trde_hist', 'label': '금현물거래내역', 'type': 'LIST', 'description': ''},
        {'element': '- deal_dt', 'label': '거래일자', 'type': 'String', 'description': ''},
        {'element': '- deal_no', 'label': '거래번호', 'type': 'String', 'description': ''},
        {'element': '- rmrk_nm', 'label': '적요명', 'type': 'String', 'description': ''},
        {'element': '- deal_qty', 'label': '거래수량', 'type': 'String', 'description': ''},
        {'element': '- gold_spot_vat', 'label': '금현물부가가치세', 'type': 'String', 'description': ''},
        {'element': '- exct_amt', 'label': '정산금액', 'type': 'String', 'description': ''},
        {'element': '- dly_sum', 'label': '연체합', 'type': 'String', 'description': ''},
        {'element': '- entra_remn', 'label': '예수금잔고', 'type': 'String', 'description': ''},
        {'element': '- mdia_nm', 'label': '메체구분명', 'type': 'String', 'description': ''},
        {'element': '- orig_deal_no', 'label': '원거래번호', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- uv_exrt', 'label': '거래단가', 'type': 'String', 'description': ''},
        {'element': '- cmsn', 'label': '수수료', 'type': 'String', 'description': ''},
        {'element': '- uncl_ocr', 'label': '미수(원/g)', 'type': 'String', 'description': ''},
        {'element': '- rpym_sum', 'label': '변제합', 'type': 'String', 'description': ''},
        {'element': '- spot_remn', 'label': '현물잔고', 'type': 'String', 'description': ''},
        {'element': '- proc_time', 'label': '처리시간', 'type': 'String', 'description': ''},
        {'element': '- rcpy_no', 'label': '출납번호', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '종목코드', 'type': 'String', 'description': ''},
        {'element': '- deal_amt', 'label': '거래금액', 'type': 'String', 'description': ''},
        {'element': '- tax_tot_amt', 'label': '소득/주민세', 'type': 'String', 'description': ''},
        {'element': '- cntr_dt', 'label': '체결일', 'type': 'String', 'description': ''},
        {'element': '- proc_brch_nm', 'label': '처리점', 'type': 'String', 'description': ''},
        {'element': '- prcsr', 'label': '처리자', 'type': 'String', 'description': ''},
    ],
    'kt50075': [
        {'element': 'acnt_ord_oso_prst', 'label': '계좌별주문미체결현황', 'type': 'LIST', 'description': ''},
        {'element': '- stk_bond_tp', 'label': '주식채권구분', 'type': 'String', 'description': ''},
        {'element': '- ord_no', 'label': '주문번호', 'type': 'String', 'description': ''},
        {'element': '- stk_cd', 'label': '상품코드', 'type': 'String', 'description': ''},
        {'element': '- trde_tp', 'label': '매매구분', 'type': 'String', 'description': ''},
        {'element': '- io_tp_nm', 'label': '주문유형구분', 'type': 'String', 'description': ''},
        {'element': '- ord_qty', 'label': '주문수량', 'type': 'String', 'description': ''},
        {'element': '- ord_uv', 'label': '주문단가', 'type': 'String', 'description': ''},
        {'element': '- cnfm_qty', 'label': '확인수량', 'type': 'String', 'description': ''},
        {'element': '- data_send_end_tp', 'label': '접수구분', 'type': 'String', 'description': ''},
        {'element': '- mrkt_deal_tp', 'label': '시장구분', 'type': 'String', 'description': ''},
        {'element': '- rsrv_tp', 'label': '예약/반대여부', 'type': 'String', 'description': ''},
        {'element': '- orig_ord_no', 'label': '원주문번호', 'type': 'String', 'description': ''},
        {'element': '- stk_nm', 'label': '종목명', 'type': 'String', 'description': ''},
        {'element': '- dcd_tp_nm', 'label': '결제구분', 'type': 'String', 'description': ''},
        {'element': '- crd_deal_tp', 'label': '신용거래구분', 'type': 'String', 'description': ''},
        {'element': '- cntr_qty', 'label': '체결수량', 'type': 'String', 'description': ''},
        {'element': '- cntr_uv', 'label': '체결단가', 'type': 'String', 'description': ''},
        {'element': '- ord_remnq', 'label': '미체결수량', 'type': 'String', 'description': ''},
        {'element': '- comm_ord_tp', 'label': '통신구분', 'type': 'String', 'description': ''},
        {'element': '- mdfy_cncl_tp', 'label': '정정취소구분', 'type': 'String', 'description': ''},
        {'element': '- dmst_stex_tp', 'label': '국내거래소구분', 'type': 'String', 'description': ''},
        {'element': '- cond_uv', 'label': '스톱가', 'type': 'String', 'description': ''},
    ],
}
